In [1]:
import xarray as xr
import glob

In [2]:
ds = xr.open_mfdataset(glob.glob("/home/quinn/t-route-inputs/*.CHRTOUT_DOMAIN1"))

KeyboardInterrupt:

In [ ]:
ds_not_fixed = xr.open_mfdataset(glob.glob("Not_Fixed/*"))

/tmp/ipykernel_95165/1615431751.py:1: FutureWarning: In a future version of xarray the default value for data_vars will change from data_vars='all' to data_vars=None. This is likely to lead to different results when multiple datasets have matching variables with overlapping values. To opt in to new defaults and get rid of these warnings now use `set_options(use_new_combine_kwarg_defaults=True) or set data_vars explicitly.
  ds_not_fixed = xr.open_mfdataset(glob.glob("Not_Fixed/*"))

In [ ]:
ds_fixed = xr.open_mfdataset(glob.glob("Fixed/*"))

In [ ]:
(ds_fixed == ds_not_fixed).flow.values

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ...,  True,  True,  True],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [ ]:
time_intersection  = set(ds['time'].values) & set(ds_fixed['time'].values)

In [ ]:
feature_intersection = set(ds['feature_id'].values) & set(ds_fixed['feature_id'].values)

In [ ]:
time_intersection

{numpy.datetime64('1979-02-06T19:00:00.000000000'),
 numpy.datetime64('1979-02-06T20:00:00.000000000'),
 numpy.datetime64('1979-02-06T21:00:00.000000000'),
 numpy.datetime64('1979-02-06T22:00:00.000000000'),
 numpy.datetime64('1979-02-06T23:00:00.000000000'),
 numpy.datetime64('1979-02-07T00:00:00.000000000'),
 numpy.datetime64('1979-02-07T01:00:00.000000000'),
 numpy.datetime64('1979-02-07T02:00:00.000000000'),
 numpy.datetime64('1979-02-07T03:00:00.000000000'),
 numpy.datetime64('1979-02-07T04:00:00.000000000'),
 numpy.datetime64('1979-02-07T05:00:00.000000000'),
 numpy.datetime64('1979-02-07T06:00:00.000000000'),
 numpy.datetime64('1979-02-07T07:00:00.000000000'),
 numpy.datetime64('1979-02-07T08:00:00.000000000'),
 numpy.datetime64('1979-02-07T09:00:00.000000000'),
 numpy.datetime64('1979-02-07T10:00:00.000000000'),
 numpy.datetime64('1979-02-07T11:00:00.000000000'),
 numpy.datetime64('1979-02-07T12:00:00.000000000'),
 numpy.datetime64('1979-02-07T13:00:00.000000000'),
 numpy.datetime64('1979-02-07T14:00:00.000000000'),
 numpy.datetime64('1979-02-07T15:00:00.000000000'),
 numpy.datetime64('1979-02-07T16:00:00.000000000'),
 numpy.datetime64('1979-02-07T17:00:00.000000000'),
 numpy.datetime64('1979-02-07T18:00:00.000000000'),
 numpy.datetime64('1979-02-07T19:00:00.000000000'),
 numpy.datetime64('1979-02-07T20:00:00.000000000'),
 numpy.datetime64('1979-02-07T21:00:00.000000000'),
 numpy.datetime64('1979-02-07T22:00:00.000000000'),
 numpy.datetime64('1979-02-07T23:00:00.000000000'),
 numpy.datetime64('1979-02-08T00:00:00.000000000'),
 numpy.datetime64('1979-02-08T01:00:00.000000000'),
 numpy.datetime64('1979-02-08T02:00:00.000000000'),
 numpy.datetime64('1979-02-08T03:00:00.000000000'),
 numpy.datetime64('1979-02-08T04:00:00.000000000'),
 numpy.datetime64('1979-02-08T05:00:00.000000000'),
 numpy.datetime64('1979-02-08T06:00:00.000000000'),
 numpy.datetime64('1979-02-08T07:00:00.000000000'),
 numpy.datetime64('1979-02-08T08:00:00.000000000'),
 numpy.datetime64('1979-02-08T09:00:00.000000000'),
 numpy.datetime64('1979-02-08T10:00:00.000000000'),
 numpy.datetime64('1979-02-08T11:00:00.000000000'),
 numpy.datetime64('1979-02-08T12:00:00.000000000'),
 numpy.datetime64('1979-02-08T13:00:00.000000000'),
 numpy.datetime64('1979-02-08T14:00:00.000000000'),
 numpy.datetime64('1979-02-08T15:00:00.000000000'),
 numpy.datetime64('1979-02-08T16:00:00.000000000'),
 numpy.datetime64('1979-02-08T17:00:00.000000000'),
 numpy.datetime64('1979-02-08T18:00:00.000000000'),
 numpy.datetime64('1979-02-08T19:00:00.000000000'),
 numpy.datetime64('1979-02-08T20:00:00.000000000'),
 numpy.datetime64('1979-02-08T21:00:00.000000000'),
 numpy.datetime64('1979-02-08T22:00:00.000000000'),
 numpy.datetime64('1979-02-08T23:00:00.000000000'),
 numpy.datetime64('1979-02-09T00:00:00.000000000'),
 numpy.datetime64('1979-02-09T01:00:00.000000000'),
 numpy.datetime64('1979-02-09T02:00:00.000000000'),
 numpy.datetime64('1979-02-09T03:00:00.000000000'),
 numpy.datetime64('1979-02-09T04:00:00.000000000'),
 numpy.datetime64('1979-02-09T05:00:00.000000000'),
 numpy.datetime64('1979-02-09T06:00:00.000000000'),
 numpy.datetime64('1979-02-09T07:00:00.000000000'),
 numpy.datetime64('1979-02-09T08:00:00.000000000'),
 numpy.datetime64('1979-02-09T09:00:00.000000000'),
 numpy.datetime64('1979-02-09T10:00:00.000000000'),
 numpy.datetime64('1979-02-09T11:00:00.000000000'),
 numpy.datetime64('1979-02-09T12:00:00.000000000'),
 numpy.datetime64('1979-02-09T13:00:00.000000000'),
 numpy.datetime64('1979-02-09T14:00:00.000000000'),
 numpy.datetime64('1979-02-09T15:00:00.000000000'),
 numpy.datetime64('1979-02-09T16:00:00.000000000'),
 numpy.datetime64('1979-02-09T17:00:00.000000000'),
 numpy.datetime64('1979-02-09T18:00:00.000000000'),
 numpy.datetime64('1979-02-09T19:00:00.000000000'),
 numpy.datetime64('1979-02-09T20:00:00.000000000'),
 numpy.datetime64('1979-02-09T21:00:00.000000000'),
 numpy.datetime64('1979-02-09T22:00:00.000000000'),
 numpy.datetime64('1979-02-09T23:00:00.000000000'),
 numpy.datetime64('1979-02-10T00:00:00.000000000'),
 numpy.datetime64('1979-02-10T01:00:00.000000000'),
 numpy.datetime64('1979-02-10T02:00:00.000000000'),
 numpy.datetime64('1979-02-10T03:00:00.000000000'),
 numpy.datetime64('1979-02-10T04:00:00.000000000'),
 numpy.datetime64('1979-02-10T05:00:00.000000000'),
 numpy.datetime64('1979-02-10T06:00:00.000000000'),
 numpy.datetime64('1979-02-10T07:00:00.000000000'),
 numpy.datetime64('1979-02-10T08:00:00.000000000'),
 numpy.datetime64('1979-02-10T09:00:00.000000000'),
 numpy.datetime64('1979-02-10T10:00:00.000000000'),
 numpy.datetime64('1979-02-10T11:00:00.000000000'),
 numpy.datetime64('1979-02-10T12:00:00.000000000'),
 numpy.datetime64('1979-02-10T13:00:00.000000000'),
 numpy.datetime64('1979-02-10T14:00:00.000000000'),
 numpy.datetime64('1979-02-10T15:00:00.000000000'),
 numpy.datetime64('1979-02-10T16:00:00.000000000'),
 numpy.datetime64('1979-02-10T17:00:00.000000000'),
 numpy.datetime64('1979-02-10T18:00:00.000000000'),
 numpy.datetime64('1979-02-10T19:00:00.000000000'),
 numpy.datetime64('1979-02-10T20:00:00.000000000'),
 numpy.datetime64('1979-02-10T21:00:00.000000000'),
 numpy.datetime64('1979-02-10T22:00:00.000000000'),
 numpy.datetime64('1979-02-10T23:00:00.000000000'),
 numpy.datetime64('1979-02-11T00:00:00.000000000'),
 numpy.datetime64('1979-02-11T01:00:00.000000000'),
 numpy.datetime64('1979-02-11T02:00:00.000000000'),
 numpy.datetime64('1979-02-11T03:00:00.000000000'),
 numpy.datetime64('1979-02-11T04:00:00.000000000'),
 numpy.datetime64('1979-02-11T05:00:00.000000000'),
 numpy.datetime64('1979-02-11T06:00:00.000000000'),
 numpy.datetime64('1979-02-11T07:00:00.000000000'),
 numpy.datetime64('1979-02-11T08:00:00.000000000'),
 numpy.datetime64('1979-02-11T09:00:00.000000000'),
 numpy.datetime64('1979-02-11T10:00:00.000000000'),
 numpy.datetime64('1979-02-11T11:00:00.000000000'),
 numpy.datetime64('1979-02-11T12:00:00.000000000'),
 numpy.datetime64('1979-02-11T13:00:00.000000000'),
 numpy.datetime64('1979-02-11T14:00:00.000000000'),
 numpy.datetime64('1979-02-11T15:00:00.000000000'),
 numpy.datetime64('1979-02-11T16:00:00.000000000'),
 numpy.datetime64('1979-02-11T17:00:00.000000000'),
 numpy.datetime64('1979-02-11T18:00:00.000000000'),
 numpy.datetime64('1979-02-11T19:00:00.000000000'),
 numpy.datetime64('1979-02-11T20:00:00.000000000'),
 numpy.datetime64('1979-02-11T21:00:00.000000000'),
 numpy.datetime64('1979-02-11T22:00:00.000000000'),
 numpy.datetime64('1979-02-11T23:00:00.000000000'),
 numpy.datetime64('1979-02-12T00:00:00.000000000'),
 numpy.datetime64('1979-02-12T01:00:00.000000000'),
 numpy.datetime64('1979-02-12T02:00:00.000000000'),
 numpy.datetime64('1979-02-12T03:00:00.000000000'),
 numpy.datetime64('1979-02-12T04:00:00.000000000'),
 numpy.datetime64('1979-02-12T05:00:00.000000000'),
 numpy.datetime64('1979-02-12T06:00:00.000000000'),
 numpy.datetime64('1979-02-12T07:00:00.000000000'),
 numpy.datetime64('1979-02-12T08:00:00.000000000'),
 numpy.datetime64('1979-02-12T09:00:00.000000000'),
 numpy.datetime64('1979-02-12T10:00:00.000000000'),
 numpy.datetime64('1979-02-12T11:00:00.000000000'),
 numpy.datetime64('1979-02-12T12:00:00.000000000'),
 numpy.datetime64('1979-02-12T13:00:00.000000000'),
 numpy.datetime64('1979-02-12T14:00:00.000000000'),
 numpy.datetime64('1979-02-12T15:00:00.000000000'),
 numpy.datetime64('1979-02-12T16:00:00.000000000'),
 numpy.datetime64('1979-02-12T17:00:00.000000000'),
 numpy.datetime64('1979-02-12T18:00:00.000000000'),
 numpy.datetime64('1979-02-12T19:00:00.000000000'),
 numpy.datetime64('1979-02-12T20:00:00.000000000'),
 numpy.datetime64('1979-02-12T21:00:00.000000000'),
 numpy.datetime64('1979-02-12T22:00:00.000000000'),
 numpy.datetime64('1979-02-12T23:00:00.000000000'),
 numpy.datetime64('1979-02-13T00:00:00.000000000'),
 numpy.datetime64('1979-02-13T01:00:00.000000000'),
 numpy.datetime64('1979-02-13T02:00:00.000000000'),
 numpy.datetime64('1979-02-13T03:00:00.000000000'),
 numpy.datetime64('1979-02-13T04:00:00.000000000'),
 numpy.datetime64('1979-02-13T05:00:00.000000000'),
 numpy.datetime64('1979-02-13T06:00:00.000000000'),
 numpy.datetime64('1979-02-13T07:00:00.000000000'),
 numpy.datetime64('1979-02-13T08:00:00.000000000'),
 numpy.datetime64('1979-02-13T09:00:00.000000000'),
 numpy.datetime64('1979-02-13T10:00:00.000000000'),
 numpy.datetime64('1979-02-13T11:00:00.000000000'),
 numpy.datetime64('1979-02-13T12:00:00.000000000'),
 numpy.datetime64('1979-02-13T13:00:00.000000000'),
 numpy.datetime64('1979-02-13T14:00:00.000000000'),
 numpy.datetime64('1979-02-13T15:00:00.000000000'),
 numpy.datetime64('1979-02-13T16:00:00.000000000'),
 numpy.datetime64('1979-02-13T17:00:00.000000000'),
 numpy.datetime64('1979-02-13T18:00:00.000000000')}

In [ ]:
flow_fixed = ds_fixed.sel(time=list(time_intersection), feature_id=list(feature_intersection)).flow.values

In [ ]:
flow_fixed

array([[1.9769861e-05, 4.3320459e-05, 6.2401174e-05, ..., 1.2999956e-04,
        1.3999942e-04, 1.2999956e-04],
       [8.0935664e-05, 5.3243816e-04, 8.3232700e-04, ..., 1.8864432e-02,
        2.1345016e-02, 1.0995111e-02],
       [6.0221455e-06, 1.4589416e-05, 2.1468917e-05, ..., 2.9999999e-05,
        3.9622664e-05, 2.9999999e-05],
       ...,
       [2.5166819e-05, 3.2707954e-05, 3.6430760e-05, ..., 3.9999952e-05,
        3.9999952e-05, 3.9999952e-05],
       [9.0179201e-06, 1.3904510e-05, 2.0747597e-05, ..., 5.9999958e-05,
        5.9999958e-05, 5.9999958e-05],
       [5.9573789e-04, 1.3522239e-04, 9.2513725e-04, ..., 2.2370245e-02,
        2.7394382e-02, 1.3048367e-02]], dtype=float32)

In [ ]:
actual_flow = ds.sel(time=list(time_intersection), feature_id=list(feature_intersection)).streamflow.values

In [ ]:
actual_flow = actual_flow.transpose()

In [ ]:
actual_flow

array([[0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
       [0.02, 0.02, 0.02, ..., 0.02, 0.02, 0.02],
       [0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
       ...,
       [0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
       [0.03, 0.03, 0.03, ..., 0.03, 0.03, 0.03]])

In [ ]:
flow_not_fixed = ds_not_fixed.sel(time=list(time_intersection), feature_id=list(feature_intersection)).flow.values

In [ ]:
flow_not_fixed

array([[1.26637751e-04, 1.54318346e-04, 1.73214110e-04, ...,
        2.39999616e-04, 2.59999448e-04, 2.39999616e-04],
       [1.05340885e-04, 8.68349453e-04, 5.65405004e-04, ...,
        1.80840530e-02, 2.07676012e-02, 9.85350553e-03],
       [2.90991666e-05, 4.48295941e-05, 5.22179980e-05, ...,
        5.99999730e-05, 7.95223605e-05, 5.99999730e-05],
       ...,
       [2.51668189e-05, 3.27079542e-05, 3.64307598e-05, ...,
        3.99999517e-05, 3.99999517e-05, 3.99999517e-05],
       [2.63961228e-05, 3.99593773e-05, 6.19718412e-05, ...,
        1.19999801e-04, 1.19999801e-04, 1.19999801e-04],
       [6.27143541e-04, 9.01143474e-04, 8.08240147e-04, ...,
        1.97295621e-02, 2.54192520e-02, 9.96895600e-03]], dtype=float32)

In [ ]:
import numpy as np

#replace nans with zeros
actual_flow = np.nan_to_num(actual_flow)
# flow_fixed = np.nan_to_num(flow_fixed)
# flow_not_fixed = np.nan_to_num(flow_not_fixed)

In [ ]:
actual_flow.shape, flow_not_fixed.shape

((1133011, 168), (1133011, 168))

In [ ]:
MAE_Fixed = abs(flow_fixed - actual_flow).mean()

In [ ]:
MAE_Fixed

10.71802690381937

In [ ]:
MAE_NOT_Fixed = abs(flow_not_fixed - actual_flow).mean()

In [ ]:
print(f"MAE Fixed: {MAE_Fixed}")
print(f"MAE Not Fixed: {MAE_NOT_Fixed}")

MAE Fixed: 10.71802690381937
MAE Not Fixed: 10.728604953096328

In [ ]:
MAE_between_Fixed_and_NotFixed = abs(flow_fixed - flow_not_fixed).mean()

In [ ]:
MAE_between_Fixed_and_NotFixed

0.07258586

In [1]:
import geopandas as gpd

layers = gpd.list_layers("/home/quinn/vpu_gpkgs/vpu-11_subset.gpkg")

In [2]:
layers

                     name geometry_type
0               flowpaths       Unknown
1                 divides       Polygon
2                   lakes         Point
3          hydrolocations         Point
4                   nexus         Point
5                    pois          None
6     flowpath-attributes          None
7  flowpath-attributes-ml          None
8                 network          None
9       divide-attributes          None

In [3]:
flowpaths_df = gpd.read_file("/home/quinn/vpu_gpkgs/vpu-11_subset.gpkg", layer = "flowpaths")

In [4]:
flowpaths_df

,id,toid,mainstem,order,hydroseq,lengthkm,areasqkm,tot_drainage_areasqkm,has_divide,divide_id,poi_id,vpuid,geometry
0,wb-2153252,nex-1328770,507432.0,3.0,63060,11.305485,7.348950,613.849719,True,cat-2153252,52371,11,"MULTILINESTRING ((373023.86 1256414.249, 37305..."
1,wb-2153439,nex-1328770,507725.0,8.0,24107,5.578091,10.671418,397443.897712,True,cat-2153439,None,11,"MULTILINESTRING ((374271.972 1250886.093, 3746..."
2,wb-2192407,nex-1329257,644110.0,7.0,16377,0.680096,0.505800,57880.415749,True,cat-2192407,88279,11,"MULTILINESTRING ((411954.615 1357026.924, 4119..."
3,wb-2137333,nex-1312319,195174.0,6.0,1,1.831641,0.836179,171589.581129,True,cat-2137333,86982,11,"MULTILINESTRING ((336175.919 923851.132, 33638..."
4,wb-2153292,nex-2153289,507676.0,1.0,63130,3.309953,5.915700,5.915700,True,cat-2153292,None,11,"MULTILINESTRING ((364605.98 1265046.189, 36462..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
63125,wb-2137341,nex-2137331,195194.0,4.0,6,11.704539,9.386551,236.121952,True,cat-2137341,None,11,"MULTILINESTRING ((309330.583 923321.736, 30932..."
63126,wb-2137331,nex-2137332,195174.0,6.0,5,28.146897,25.386131,170501.603331,True,cat-2137331,None,11,"MULTILINESTRING ((314329.249 930014.317, 31481..."
63127,wb-2137332,nex-2137333,195174.0,6.0,4,6.647261,6.014250,171573.894950,True,cat-2137332,31746,11,"MULTILINESTRING ((332634.253 924673.308, 33276..."
63128,wb-2137334,nex-2137335,195175.0,1.0,3,6.647979,9.198450,9.198450,True,cat-2137334,None,11,"MULTILINESTRING ((337695.985 929617.825, 33775..."
63129,wb-2137335,nex-2137333,195175.0,1.0,2,1.676074,5.651550,14.850000,True,cat-2137335,None,11,"MULTILINESTRING ((337586.806 924631.737, 33730..."

In [5]:
flowpath_attributes_df = gpd.read_file("/home/quinn/vpu_gpkgs/vpu-11_subset.gpkg", layer = "flowpath-attributes")

In [6]:
flowpath_attributes_df

,link,to,Length_m,Y,n,nCC,BtmWdth,TopWdth,TopWdthCC,ChSlp,...,So,MusX,MusK,gage,gage_nex_id,WaterbodyID,waterbody_nex_id,id,toid,vpuid
0,wb-2153252,nex-1328770,11305.484744,1.039577,0.055,0.11,21.643671,21.698170,65.094509,0.026212,...,0.000195,0.2,3600.0,None,None,None,None,wb-2153252,nex-1328770,11
1,wb-2153439,nex-1328770,5578.091248,4.047731,0.045,0.09,148.451774,195.498581,586.495743,5.811503,...,0.000749,0.2,3600.0,None,None,None,None,wb-2153439,nex-1328770,11
2,wb-2192407,nex-1329257,680.095729,2.700819,0.045,0.09,84.125101,101.543139,304.629417,3.224585,...,0.000000,0.2,3600.0,None,None,None,None,wb-2192407,nex-1329257,11
3,wb-2137333,nex-1312319,1831.641076,3.393180,0.050,0.10,115.952145,146.932117,440.796352,4.565036,...,0.000000,0.2,3600.0,None,None,None,None,wb-2137333,nex-1312319,11
4,wb-2153292,nex-2153289,3309.952775,0.392180,0.060,0.12,4.465519,5.346751,16.040252,1.123505,...,0.000746,0.2,3600.0,None,None,None,None,wb-2153292,nex-2153289,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63135,wb-2137341,nex-2137331,11704.539298,0.850594,0.055,0.11,15.640700,16.284316,48.852949,0.378333,...,0.000360,0.2,3600.0,None,None,None,None,wb-2137341,nex-2137331,11
63136,wb-2137331,nex-2137332,28146.897400,3.388650,0.050,0.10,115.735023,146.614696,439.844089,4.556338,...,0.000009,0.2,3600.0,None,None,None,None,wb-2137331,nex-2137332,11
63137,wb-2137332,nex-2137333,6647.260927,3.393115,0.050,0.10,115.949021,146.927550,440.782651,4.564911,...,0.000008,0.2,3600.0,None,None,None,None,wb-2137332,nex-2137333,11
63138,wb-2137334,nex-2137335,6647.978680,0.430273,0.060,0.12,5.188631,6.112351,18.337052,1.073412,...,0.003398,0.2,3600.0,None,None,None,None,wb-2137334,nex-2137335,11
63139,wb-2137335,nex-2137333,1676.074424,0.475802,0.060,0.12,6.106281,7.066575,21.199725,1.009131,...,0.002992,0.2,3600.0,None,None,None,None,wb-2137335,nex-2137333,11

In [7]:
flowpaths_df["id"]

0        wb-2153252
1        wb-2153439
2        wb-2192407
3        wb-2137333
4        wb-2153292
            ...
63125    wb-2137341
63126    wb-2137331
63127    wb-2137332
63128    wb-2137334
63129    wb-2137335
Name: id, Length: 63130, dtype: object

In [8]:
flowpath_attributes_df["id"]

0        wb-2153252
1        wb-2153439
2        wb-2192407
3        wb-2137333
4        wb-2153292
            ...
63135    wb-2137341
63136    wb-2137331
63137    wb-2137332
63138    wb-2137334
63139    wb-2137335
Name: id, Length: 63140, dtype: object

In [9]:
unique_cols = set(flowpath_attributes_df.columns).difference(set(flowpaths_df.columns))
unique_cols.add("id")

In [10]:
import pandas as pd
flowpath_attributes_df = flowpath_attributes_df[list(unique_cols)]
flowpaths = pd.merge(
    flowpaths_df, 
    flowpath_attributes_df, 
    on='id', 
    how='inner'
)

In [11]:
unique_cols

{'BtmWdth',
 'ChSlp',
 'Length_m',
 'MusK',
 'MusX',
 'So',
 'TopWdth',
 'TopWdthCC',
 'WaterbodyID',
 'Y',
 'alt',
 'gage',
 'gage_nex_id',
 'id',
 'link',
 'n',
 'nCC',
 'to',
 'waterbody_nex_id'}

In [12]:
flowpaths.columns

Index(['id', 'toid', 'mainstem', 'order', 'hydroseq', 'lengthkm', 'areasqkm',
       'tot_drainage_areasqkm', 'has_divide', 'divide_id', 'poi_id', 'vpuid',
       'geometry', 'link', 'nCC', 'TopWdthCC', 'TopWdth', 'gage_nex_id',
       'ChSlp', 'Y', 'n', 'MusX', 'So', 'Length_m', 'WaterbodyID', 'BtmWdth',
       'waterbody_nex_id', 'alt', 'to', 'MusK', 'gage'],
      dtype='object')

In [13]:
flowpaths['alt']

0        57.520000
1        59.490002
2        55.560001
3        19.469999
4        65.412453
           ...
63135    23.997187
63136    19.784386
63137    19.520000
63138    47.071301
63139    24.484371
Name: alt, Length: 63140, dtype: float64

In [14]:
mask = ~flowpaths['toid'].str.startswith("tnx")

In [15]:
flowpath_dict = dict(zip(flowpaths.loc[mask].toid, flowpaths.loc[mask].id))

In [16]:
flowpaths[flowpaths['toid'].str.startswith("tnx")]

,id,toid,mainstem,order,hydroseq,lengthkm,areasqkm,tot_drainage_areasqkm,has_divide,divide_id,...,MusX,So,Length_m,WaterbodyID,BtmWdth,waterbody_nex_id,alt,to,MusK,gage
39041,wb-2199817,tnx-1000006130,2431325.0,2.0,24100,5.482847,6.698699,216.022950,True,cat-2199817,...,0.2,0.001764,5482.846745,None,15.174689,None,1136.171875,tnx-1000006130,3600.0,None
39042,wb-2199821,tnx-1000006103,2469441.0,1.0,24099,9.006460,11.788649,11.788649,True,cat-2199821,...,0.2,0.006309,9006.459567,None,5.645307,None,685.697083,tnx-1000006103,3600.0,None
39046,wb-2199824,tnx-1000006104,2469455.0,1.0,24095,2.727379,3.208500,3.208500,True,cat-2199824,...,0.2,0.014666,2727.378591,None,3.626874,None,654.447205,tnx-1000006104,3600.0,None
39047,wb-2199823,tnx-1000006104,2469452.0,1.0,24094,2.868677,3.520800,3.520800,True,cat-2199823,...,0.2,0.012556,2868.676692,None,3.743242,None,676.604309,tnx-1000006104,3600.0,None
39048,wb-2199822,tnx-1000006104,2469444.0,2.0,24093,9.647218,7.551000,35.474850,True,cat-2199822,...,0.2,0.007360,9647.218259,None,8.210372,None,684.124817,tnx-1000006104,3600.0,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46858,wb-2199848,tnx-1000006173,2469514.0,1.0,16283,1.850402,5.434200,5.434200,True,cat-2199848,...,0.2,0.012404,1850.401987,None,4.338463,None,803.016296,tnx-1000006173,3600.0,None
46859,wb-2199830,tnx-1000006105,2469472.0,1.0,16282,3.027445,4.750200,4.750200,True,cat-2199830,...,0.2,0.018803,3027.445358,None,4.144497,None,678.160828,tnx-1000006105,3600.0,None
46862,wb-2199832,tnx-1000006174,2469475.0,2.0,16279,7.444511,70.389900,83.205000,True,cat-2199832,...,0.2,0.003667,7444.511216,None,10.970859,None,678.263794,tnx-1000006174,3600.0,None
46864,wb-2199837,tnx-1000006106,2469489.0,1.0,16277,4.514317,14.509801,17.551350,True,cat-2199837,...,0.2,0.002051,4514.317489,None,6.463316,None,790.187927,tnx-1000006106,3600.0,None
46887,wb-2199798,tnx-1000006175,2431300.0,3.0,16254,0.373887,0.215100,225.607498,True,cat-2199798,...,0.2,0.003986,373.886686,None,15.400330,None,1435.451904,tnx-1000006175,3600.0,None

In [17]:
flowpaths[flowpaths["toid"].isin(flowpaths.id)]

Empty GeoDataFrame
Columns: [id, toid, mainstem, order, hydroseq, lengthkm, areasqkm, tot_drainage_areasqkm, has_divide, divide_id, poi_id, vpuid, geometry, link, nCC, TopWdthCC, TopWdth, gage_nex_id, ChSlp, Y, n, MusX, So, Length_m, WaterbodyID, BtmWdth, waterbody_nex_id, alt, to, MusK, gage]
Index: []

[0 rows x 31 columns]

In [18]:
flowpaths

,id,toid,mainstem,order,hydroseq,lengthkm,areasqkm,tot_drainage_areasqkm,has_divide,divide_id,...,MusX,So,Length_m,WaterbodyID,BtmWdth,waterbody_nex_id,alt,to,MusK,gage
0,wb-2153252,nex-1328770,507432.0,3.0,63060,11.305485,7.348950,613.849719,True,cat-2153252,...,0.2,0.000195,11305.484744,None,21.643671,None,57.520000,nex-1328770,3600.0,None
1,wb-2153439,nex-1328770,507725.0,8.0,24107,5.578091,10.671418,397443.897712,True,cat-2153439,...,0.2,0.000749,5578.091248,None,148.451774,None,59.490002,nex-1328770,3600.0,None
2,wb-2192407,nex-1329257,644110.0,7.0,16377,0.680096,0.505800,57880.415749,True,cat-2192407,...,0.2,0.000000,680.095729,None,84.125101,None,55.560001,nex-1329257,3600.0,None
3,wb-2137333,nex-1312319,195174.0,6.0,1,1.831641,0.836179,171589.581129,True,cat-2137333,...,0.2,0.000000,1831.641076,None,115.952145,None,19.469999,nex-1312319,3600.0,None
4,wb-2153292,nex-2153289,507676.0,1.0,63130,3.309953,5.915700,5.915700,True,cat-2153292,...,0.2,0.000746,3309.952775,None,4.465519,None,65.412453,nex-2153289,3600.0,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63135,wb-2137341,nex-2137331,195194.0,4.0,6,11.704539,9.386551,236.121952,True,cat-2137341,...,0.2,0.000360,11704.539298,None,15.640700,None,23.997187,nex-2137331,3600.0,None
63136,wb-2137331,nex-2137332,195174.0,6.0,5,28.146897,25.386131,170501.603331,True,cat-2137331,...,0.2,0.000009,28146.897400,None,115.735023,None,19.784386,nex-2137332,3600.0,None
63137,wb-2137332,nex-2137333,195174.0,6.0,4,6.647261,6.014250,171573.894950,True,cat-2137332,...,0.2,0.000008,6647.260927,None,115.949021,None,19.520000,nex-2137333,3600.0,None
63138,wb-2137334,nex-2137335,195175.0,1.0,3,6.647979,9.198450,9.198450,True,cat-2137334,...,0.2,0.003398,6647.978680,None,5.188631,None,47.071301,nex-2137335,3600.0,None
63139,wb-2137335,nex-2137333,195175.0,1.0,2,1.676074,5.651550,14.850000,True,cat-2137335,...,0.2,0.002992,1676.074424,None,6.106281,None,24.484371,nex-2137333,3600.0,None

In [24]:
flowpaths[flowpaths['toid'].str.startswith('tnx-')]

,id,toid,mainstem,order,hydroseq,lengthkm,areasqkm,tot_drainage_areasqkm,has_divide,divide_id,...,MusX,So,Length_m,WaterbodyID,BtmWdth,waterbody_nex_id,alt,to,MusK,gage
39041,wb-2199817,tnx-1000006130,2431325.0,2.0,24100,5.482847,6.698699,216.022950,True,cat-2199817,...,0.2,0.001764,5482.846745,None,15.174689,None,1136.171875,tnx-1000006130,3600.0,None
39042,wb-2199821,tnx-1000006103,2469441.0,1.0,24099,9.006460,11.788649,11.788649,True,cat-2199821,...,0.2,0.006309,9006.459567,None,5.645307,None,685.697083,tnx-1000006103,3600.0,None
39046,wb-2199824,tnx-1000006104,2469455.0,1.0,24095,2.727379,3.208500,3.208500,True,cat-2199824,...,0.2,0.014666,2727.378591,None,3.626874,None,654.447205,tnx-1000006104,3600.0,None
39047,wb-2199823,tnx-1000006104,2469452.0,1.0,24094,2.868677,3.520800,3.520800,True,cat-2199823,...,0.2,0.012556,2868.676692,None,3.743242,None,676.604309,tnx-1000006104,3600.0,None
39048,wb-2199822,tnx-1000006104,2469444.0,2.0,24093,9.647218,7.551000,35.474850,True,cat-2199822,...,0.2,0.007360,9647.218259,None,8.210372,None,684.124817,tnx-1000006104,3600.0,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46858,wb-2199848,tnx-1000006173,2469514.0,1.0,16283,1.850402,5.434200,5.434200,True,cat-2199848,...,0.2,0.012404,1850.401987,None,4.338463,None,803.016296,tnx-1000006173,3600.0,None
46859,wb-2199830,tnx-1000006105,2469472.0,1.0,16282,3.027445,4.750200,4.750200,True,cat-2199830,...,0.2,0.018803,3027.445358,None,4.144497,None,678.160828,tnx-1000006105,3600.0,None
46862,wb-2199832,tnx-1000006174,2469475.0,2.0,16279,7.444511,70.389900,83.205000,True,cat-2199832,...,0.2,0.003667,7444.511216,None,10.970859,None,678.263794,tnx-1000006174,3600.0,None
46864,wb-2199837,tnx-1000006106,2469489.0,1.0,16277,4.514317,14.509801,17.551350,True,cat-2199837,...,0.2,0.002051,4514.317489,None,6.463316,None,790.187927,tnx-1000006106,3600.0,None
46887,wb-2199798,tnx-1000006175,2431300.0,3.0,16254,0.373887,0.215100,225.607498,True,cat-2199798,...,0.2,0.003986,373.886686,None,15.400330,None,1435.451904,tnx-1000006175,3600.0,None

In [25]:
def numeric_id(flowpath):
    id = flowpath['id'].split('-')[-1]
    toid = flowpath['toid'].split('-')[-1]
    flowpath['id'] = int(float(id))
    flowpath['toid'] = int(float(toid))
    return flowpath

In [26]:
flowpaths2 = flowpaths.apply(numeric_id, axis=1)
# toid = flowpaths['toid'].split('-')[-1]
# flowpaths['id'] = int(float(id))
# flowpaths['toid'] = int(float(toid))

In [27]:
flowpaths2[flowpaths2["toid"].isin(flowpaths2.id)]

,id,toid,mainstem,order,hydroseq,lengthkm,areasqkm,tot_drainage_areasqkm,has_divide,divide_id,...,MusX,So,Length_m,WaterbodyID,BtmWdth,waterbody_nex_id,alt,to,MusK,gage
4,2153292,2153289,507676.0,1.0,63130,3.309953,5.915700,5.915700,True,cat-2153292,...,0.2,0.000746,3309.952775,None,4.465519,None,65.412453,nex-2153289,3600.0,None
5,2153295,2153289,507696.0,1.0,63129,4.101923,3.110400,3.110400,True,cat-2153295,...,0.2,0.000743,4101.923103,None,3.588784,None,67.092659,nex-2153289,3600.0,None
6,2153296,2153289,507703.0,1.0,63128,2.709379,6.058350,6.058350,True,cat-2153296,...,0.2,0.000201,2709.378626,None,4.501843,None,65.097176,nex-2153289,3600.0,None
7,2153294,2153288,507689.0,1.0,63127,0.040288,0.000450,0.000450,True,cat-2153294,...,0.2,0.033463,40.287865,None,2.440000,None,65.997314,nex-2153288,3600.0,None
8,2153293,2153288,507688.0,1.0,63126,1.160837,0.636750,0.636750,True,cat-2153293,...,0.2,0.001614,1160.837083,None,2.440000,None,66.523262,nex-2153288,3600.0,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63135,2137341,2137331,195194.0,4.0,6,11.704539,9.386551,236.121952,True,cat-2137341,...,0.2,0.000360,11704.539298,None,15.640700,None,23.997187,nex-2137331,3600.0,None
63136,2137331,2137332,195174.0,6.0,5,28.146897,25.386131,170501.603331,True,cat-2137331,...,0.2,0.000009,28146.897400,None,115.735023,None,19.784386,nex-2137332,3600.0,None
63137,2137332,2137333,195174.0,6.0,4,6.647261,6.014250,171573.894950,True,cat-2137332,...,0.2,0.000008,6647.260927,None,115.949021,None,19.520000,nex-2137333,3600.0,None
63138,2137334,2137335,195175.0,1.0,3,6.647979,9.198450,9.198450,True,cat-2137334,...,0.2,0.003398,6647.978680,None,5.188631,None,47.071301,nex-2137335,3600.0,None
63139,2137335,2137333,195175.0,1.0,2,1.676074,5.651550,14.850000,True,cat-2137335,...,0.2,0.002992,1676.074424,None,6.106281,None,24.484371,nex-2137333,3600.0,None

In [28]:
df_nexus = gpd.read_file("/home/quinn/vpu_gpkgs/vpu-11_subset.gpkg", layer = "nexus")

In [29]:
df_nexus

,id,toid,type,vpuid,poi_id,geometry
0,nex-1312319,wb-1312319,nexus,11,75606.0,POINT (336709.552 922146.535)
1,nex-1312319,wb-1312319,nexus,11,86982.0,POINT (336709.552 922146.535)
2,nex-1328770,wb-1328770,nexus,11,52371.0,POINT (378844.707 1248399.774)
3,nex-1329257,wb-1329257,nexus,11,88279.0,POINT (412575.637 1356834.358)
4,nex-2136980,wb-2136980,nexus,11,52711.0,POINT (-642323.281 1326382.236)
...,...,...,...,...,...,...
29661,inx-2136935,wb-0,internal,11,NaN,POINT (-600956.252 1376580)
29662,inx-2136934,wb-0,internal,11,NaN,POINT (-463225.315 1386525)
29663,inx-2136933,wb-0,internal,11,NaN,POINT (-580412.144 1482915.003)
29664,inx-2136932,wb-0,internal,11,NaN,POINT (-562231.876 1782524.996)
29665,inx-2136931,wb-0,internal,11,NaN,POINT (-565612.498 1784940.003)

In [30]:
df_nexus[df_nexus['id'] == "tnx-1000006130"]

,id,toid,type,vpuid,poi_id,geometry
29574,tnx-1000006130,wb-0,terminal,11,NaN,POINT (-533156.849 1603369.051)

In [31]:
dict_poi = df_nexus.groupby('poi_id')['id'].apply(list).to_dict()

In [86]:
dict_poi

{56.0: ['nex-2185239'],
 57.0: ['nex-2167667'],
 58.0: ['nex-2167559'],
 59.0: ['nex-2191457'],
 60.0: ['nex-2163526'],
 61.0: ['nex-2166819'],
 62.0: ['nex-2166551'],
 63.0: ['nex-2164734'],
 64.0: ['nex-2164736'],
 65.0: ['nex-2164618'],
 66.0: ['nex-2164639'],
 67.0: ['nex-2152619'],
 68.0: ['nex-2157776'],
 69.0: ['nex-2157603'],
 71.0: ['nex-2185095'],
 72.0: ['nex-2185016'],
 73.0: ['nex-2181449'],
 74.0: ['nex-2157230'],
 75.0: ['nex-2157424'],
 76.0: ['nex-2164351'],
 77.0: ['nex-2163797'],
 78.0: ['nex-2163671'],
 79.0: ['nex-2163794'],
 80.0: ['nex-2163861'],
 81.0: ['nex-2163717'],
 82.0: ['nex-2151917'],
 83.0: ['nex-2148013'],
 84.0: ['nex-2142408'],
 85.0: ['nex-2142322'],
 88.0: ['nex-2140862'],
 89.0: ['nex-2141262'],
 92.0: ['nex-2148316'],
 93.0: ['nex-2148430'],
 94.0: ['nex-2148440'],
 95.0: ['nex-2145310'],
 96.0: ['nex-2145886'],
 97.0: ['nex-2145994'],
 98.0: ['nex-2143465'],
 145.0: ['nex-2187677'],
 146.0: ['nex-2185436'],
 147.0: ['nex-2185776'],
 148.0: ['nex-2185729'],
 151.0: ['nex-2176863'],
 152.0: ['nex-2177044'],
 153.0: ['nex-2178990'],
 154.0: ['nex-2178939'],
 155.0: ['nex-2178936'],
 156.0: ['nex-2178905'],
 157.0: ['nex-2179250'],
 158.0: ['nex-2176625'],
 159.0: ['nex-2175890'],
 160.0: ['nex-2167799'],
 161.0: ['nex-2178361'],
 162.0: ['nex-2178359'],
 163.0: ['nex-2177135'],
 164.0: ['nex-2177113'],
 165.0: ['nex-2177090'],
 166.0: ['nex-2174905'],
 167.0: ['nex-2139472'],
 168.0: ['nex-2139081'],
 169.0: ['nex-2139512'],
 170.0: ['nex-2139107'],
 171.0: ['nex-2139377'],
 199.0: ['nex-2139330'],
 233.0: ['nex-2140037'],
 234.0: ['nex-2139964'],
 235.0: ['nex-2139951'],
 236.0: ['nex-2139989'],
 237.0: ['nex-2140334'],
 238.0: ['nex-2139752'],
 280.0: ['nex-2177635'],
 308.0: ['nex-2180076'],
 319.0: ['nex-2175588'],
 320.0: ['nex-2175590'],
 870.0: ['nex-2152201'],
 871.0: ['nex-2152540'],
 872.0: ['nex-2144311'],
 980.0: ['nex-2141095'],
 981.0: ['nex-2140914'],
 982.0: ['nex-2141870'],
 983.0: ['nex-2141078'],
 984.0: ['nex-2138603'],
 985.0: ['nex-2138639'],
 1120.0: ['nex-2140355'],
 1562.0: ['nex-2139086'],
 1671.0: ['nex-2157833'],
 1672.0: ['nex-2155712'],
 1673.0: ['nex-2155762'],
 1674.0: ['nex-2155674'],
 1675.0: ['nex-2155658'],
 2191.0: ['nex-2195887'],
 2192.0: ['nex-2188608'],
 2193.0: ['nex-2198585'],
 2194.0: ['nex-2195696'],
 2195.0: ['nex-2193164'],
 2196.0: ['nex-2195802'],
 2222.0: ['nex-2155110'],
 2223.0: ['nex-2155169'],
 2224.0: ['nex-2155171'],
 2225.0: ['nex-2153395'],
 2226.0: ['nex-2154740'],
 2227.0: ['nex-2191717'],
 2228.0: ['nex-2191906'],
 2229.0: ['nex-2191713'],
 2230.0: ['nex-2191953'],
 2231.0: ['nex-2191961'],
 2232.0: ['nex-2154173'],
 2233.0: ['nex-2154544'],
 2234.0: ['nex-2154027'],
 2235.0: ['nex-2153533'],
 2236.0: ['nex-2153513'],
 2310.0: ['nex-2138031'],
 2311.0: ['nex-2138264'],
 2312.0: ['nex-2142949'],
 2313.0: ['nex-2143824'],
 2314.0: ['nex-2142862'],
 2315.0: ['nex-2144177'],
 2316.0: ['nex-2143898'],
 2317.0: ['nex-2146884'],
 2331.0: ['nex-2198403'],
 2332.0: ['nex-2192269'],
 2511.0: ['nex-2142187'],
 2512.0: ['nex-2152836'],
 2513.0: ['nex-2152863'],
 2719.0: ['nex-2193389'],
 3301.0: ['nex-2147720'],
 3302.0: ['nex-2150339'],
 3321.0: ['nex-2146464'],
 3322.0: ['nex-2146451'],
 3323.0: ['nex-2146698'],
 3324.0: ['nex-2147353'],
 3325.0: ['nex-2147281'],
 3326.0: ['nex-2147169'],
 3327.0: ['nex-2147230'],
 3328.0: ['nex-2149341'],
 3329.0: ['nex-2150875'],
 3330.0: ['nex-2151382'],
 3338.0: ['nex-2165095'],
 3348.0: ['nex-2137015'],
 3349.0: ['nex-2149671'],
 4096.0: ['nex-2137870'],
 4098.0: ['nex-2137663'],
 4099.0: ['nex-2153112'],
 4100.0: ['nex-2137620'],
 4101.0: ['nex-2137384'],
 4102.0: ['nex-2137359'],
 4103.0: ['nex-2137341'],
 4104.0: ['nex-2138380'],
 4105.0: ['nex-2138429'],
 4106.0: ['nex-2138691'],
 4107.0: ['nex-2152967'],
 4108.0: ['nex-2144795'],
 4109.0: ['nex-2144668'],
 4110.0: ['nex-2144559'],
 4111.0: ['nex-2144655'],
 4112.0: ['nex-2146187'],
 4113.0: ['nex-2156853'],
 4114.0: ['nex-2159347'],
 4115.0: ['nex-2156789'],
 4116.0: ['nex-2161002'],
 4117.0: ['nex-2156761'],
 4118.0: ['nex-2161444'],
 4119.0: ['nex-2161484'],
 4120.0: ['nex-2162138'],
 4121.0: ['nex-2161918'],
 4122.0: ['nex-2161919'],
 4123.0: ['nex-2171097'],
 4190.0: ['nex-2189281'],
 4191.0: ['nex-2189569'],
 4192.0: ['nex-2189686'],
 4193.0: ['nex-2187756'],
 4194.0: ['nex-2190493'],
 4195.0: ['nex-2190354'],
 4196.0: ['nex-2186600'],
 4197.0: ['nex-2185375'],
 4198.0: ['nex-2187389'],
 4199.0: ['nex-2168275'],
 4200.0: ['nex-2168179'],
 4201.0: ['nex-2153303'],
 4202.0: ['nex-2169001'],
 4203.0: ['nex-2169441'],
 4204.0: ['nex-2168664'],
 4205.0: ['nex-2181056'],
 4206.0: ['nex-2168021'],
 4207.0: ['nex-2183892'],
 4208.0: ['nex-2163440'],
 4209.0: ['nex-2171274'],
 4210.0: ['nex-2172052'],
 4211.0: ['nex-2171853'],
 4212.0: ['nex-2172812'],
 4213.0: ['nex-2173088'],
 4214.0: ['nex-2172966'],
 4215.0: ['nex-2180256'],
 4216.0: ['nex-2180258'],
 4217.0: ['nex-2180432'],
 4262.0: ['nex-2187045'],
 4263.0: ['nex-2186863'],
 4290.0: ['nex-2187970'],
 4291.0: ['nex-2187850'],
 4292.0: ['nex-2191261'],
 4293.0: ['nex-2191265'],
 4294.0: ['nex-2186298'],
 4295.0: ['nex-2186200'],
 4296.0: ['nex-2185819'],
 4297.0: ['nex-2185975'],
 4298.0: ['nex-2187541'],
 4334.0: ['nex-2172760'],
 4530.0: ['nex-2192026'],
 4531.0: ['nex-2153429'],
 4532.0: ['nex-2153237'],
 4533.0: ['nex-2192195'],
 4534.0: ['nex-2192244'],
 4535.0: ['nex-2153443'],
 4887.0: ['nex-2196285'],
 4889.0: ['nex-2153380'],
 4900.0: ['nex-2147176'],
 4942.0: ['nex-2137601'],
 4989.0: ['nex-2142845'],
 4994.0: ['nex-2192312'],
 5010.0: ['nex-2137945'],
 5011.0: ['nex-2138360'],
 5356.0: ['nex-2177129'],
 5357.0: ['nex-2187779'],
 5358.0: ['nex-2147337'],
 5359.0: ['nex-2192290'],
 5360.0: ['nex-2192348'],
 5361.0: ['nex-2192435'],
 5362.0: ['nex-2179712'],
 5363.0: ['nex-2172814'],
 5364.0: ['nex-2185418'],
 5365.0: ['nex-2189442'],
 5366.0: ['nex-2187840'],
 5367.0: ['nex-2187972'],
 5368.0: ['nex-2187867'],
 5369.0: ['nex-2163562'],
 5370.0: ['nex-2151949'],
 5371.0: ['nex-2147949'],
 5372.0: ['nex-2137188'],
 5373.0: ['nex-2146099'],
 5374.0: ['nex-2143911'],
 5375.0: ['nex-2140892'],
 5376.0: ['nex-2137714'],
 5377.0: ['nex-2139841'],
 5378.0: ['nex-2139124'],
 5392.0: ['nex-2137002'],
 5393.0: ['nex-2149801'],
 5394.0: ['nex-2143604'],
 5395.0: ['nex-2143689'],
 5423.0: ['nex-2157026'],
 5424.0: ['nex-2153353'],
 5425.0: ['nex-2156668'],
 5426.0: ['nex-2191951'],
 5427.0: ['nex-2175810'],
 5435.0: ['nex-2185577'],
 5453.0: ['nex-2193928'],
 5458.0: ['nex-2195176'],
 5482.0: ['nex-2193922'],
 5489.0: ['nex-2193924'],
 5500.0: ['nex-2193921'],
 5511.0: ['nex-2193918'],
 5540.0: ['nex-2185984'],
 5547.0: ['nex-2193927'],
 5590.0: ['nex-2194096'],
 5610.0: ['nex-2185859'],
 5636.0: ['nex-2185759'],
 5669.0: ['nex-2193992'],
 5678.0: ['nex-2193989'],
 5683.0: ['nex-2193495'],
 5693.0: ['nex-2193981'],
 5722.0: ['nex-2193984'],
 5728.0: ['nex-2193982'],
 5798.0: ['nex-2193934'],
 5828.0: ['nex-2193520'],
 5844.0: ['nex-2190621'],
 5861.0: ['nex-2181344'],
 5871.0: ['nex-2193517'],
 5873.0: ['nex-2193513'],
 5887.0: ['nex-2193518'],
 5909.0: ['nex-2191030'],
 5916.0: ['nex-2193516'],
 5917.0: ['nex-2193821'],
 5924.0: ['nex-2193506'],
 5931.0: ['nex-2193514'],
 5948.0: ['nex-2191199'],
 5983.0: ['nex-2147055'],
 5987.0: ['nex-2193511'],
 5991.0: ['nex-2193822'],
 5996.0: ['nex-2193510'],
 6009.0: ['nex-2193509'],
 6010.0: ['nex-2193500'],
 6018.0: ['nex-2193871'],
 6023.0: ['nex-2193593'],
 6035.0: ['nex-2193504'],
 6124.0: ['nex-2193498'],
 6127.0: ['nex-2193594'],
 6159.0: ['nex-2193987'],
 6170.0: ['nex-2193503'],
 6197.0: ['nex-2193195'],
 6252.0: ['nex-2191156'],
 6269.0: ['nex-2193717'],
 6485.0: ['nex-2193869'],
 6602.0: ['nex-2193507'],
 6743.0: ['nex-2188657'],
 7115.0: ['nex-2188645'],
 7179.0: ['nex-2194524'],
 7299.0: ['nex-2177042'],
 7667.0: ['nex-2193523'],
 7994.0: ['nex-2193980'],
 8016.0: ['nex-2153370'],
 8115.0: ['nex-2194095'],
 8458.0: ['nex-2188703'],
 8529.0: ['nex-2189175'],
 8590.0: ['nex-2188824'],
 8702.0: ['nex-2188808'],
 8719.0: ['nex-2149397'],
 8726.0: ['nex-2137213'],
 8736.0: ['nex-2141755'],
 8742.0: ['nex-2193591'],
 8753.0: ['nex-2193497'],
 8782.0: ['nex-2191325'],
 8794.0: ['nex-2193820'],
 8813.0: ['nex-2193521'],
 8822.0: ['nex-2193204'],
 8825.0: ['nex-2193205'],
 8854.0: ['nex-2193471'],
 8857.0: ['nex-2193247'],
 8861.0: ['nex-2137203'],
 8866.0: ['nex-2193246'],
 8879.0: ['nex-2193242'],
 8886.0: ['nex-2137197'],
 8918.0: ['nex-2137220'],
 8929.0: ['nex-2193241'],
 8943.0: ['nex-2137195'],
 8966.0: ['nex-2194298'],
 8969.0: ['nex-2147106'],
 8974.0: ['nex-2137101'],
 8977.0: ['nex-2195277'],
 8982.0: ['nex-2137226'],
 8991.0: ['nex-2193437'],
 8999.0: ['nex-2193435'],
 9009.0: ['nex-2193461'],
 9012.0: ['nex-2137074'],
 9014.0: ['nex-2196356'],
 9018.0: ['nex-2142864'],
 9045.0: ['nex-2199701'],
 9047.0: ['nex-2147948'],
 9056.0: ['nex-2137067'],
 9079.0: ['nex-2143030'],
 9086.0: ['nex-2192399'],
 9102.0: ['nex-2193231'],
 9107.0: ['nex-2193044'],
 9111.0: ['nex-2193331'],
 9115.0: ['nex-2143002'],
 9119.0: ['nex-2193330'],
 9135.0: ['nex-2156735'],
 9138.0: ['nex-2193329'],
 9147.0: ['nex-2193272'],
 9161.0: ['nex-2193270'],
 9173.0: ['nex-2137204'],
 9199.0: ['nex-2193252'],
 9220.0: ['nex-2143599'],
 9297.0: ['nex-2193232'],
 9366.0: ['nex-2192391'],
 9378.0: ['nex-2199705'],
 9447.0: ['nex-2142325'],
 9488.0: ['nex-2199700'],
 9491.0: ['nex-2181255'],
 9524.0: ['nex-2193234'],
 9587.0: ['nex-2192402'],
 9651.0: ['nex-2199698'],
 9986.0: ['nex-2199703'],
 10286.0: ['nex-2137385'],
 10375.0: ['nex-2193228'],
 10582.0: ['nex-2137240'],
 10588.0: ['nex-2193079'],
 10869.0: ['nex-2193235'],
 10896.0: ['nex-2193236'],
 10938.0: ['nex-2193239'],
 10958.0: ['nex-2140857'],
 10960.0: ['nex-2137232'],
 10962.0: ['nex-2137236'],
 10997.0: ['nex-2137243'],
 11001.0: ['nex-2193076'],
 11015.0: ['nex-2193074'],
 11047.0: ['nex-2137233'],
 11052.0: ['nex-2192406'],
 11062.0: ['nex-2137261'],
 11080.0: ['nex-2193016'],
 11115.0: ['nex-2192450'],
 11121.0: ['nex-2146101'],
 11130.0: ['nex-2192947'],
 11141.0: ['nex-2192441'],
 11169.0: ['nex-2192440'],
 11217.0: ['nex-2137230'],
 11237.0: ['nex-2192906'],
 11249.0: ['nex-2192437'],
 11285.0: ['nex-2164560'],
 11310.0: ['nex-2140850'],
 11328.0: ['nex-2192560'],
 11338.0: ['nex-2192420'],
 11368.0: ['nex-2192419'],
 11407.0: ['nex-2192415'],
 11425.0: ['nex-2192414'],
 11449.0: ['nex-2181284'],
 11484.0: ['nex-2192610'],
 11493.0: ['nex-2181377'],
 11513.0: ['nex-2185422'],
 11535.0: ['nex-2192403'],
 12150.0: ['nex-2146472'],
 12176.0: ['nex-2192443'],
 12261.0: ['nex-2192395'],
 12573.0: ['nex-2157669'],
 12729.0: ['nex-2192422'],
 12799.0: ['nex-2137235'],
 12801.0: ['nex-2192411'],
 12872.0: ['nex-2192564'],
 12876.0: ['nex-2161544'],
 12889.0: ['nex-2192749'],
 12937.0: ['nex-2192748'],
 12963.0: ['nex-2161599'],
 12968.0: ['nex-2192826'],
 13023.0: ['nex-2194446'],
 13024.0: ['nex-2192446'],
 13030.0: ['nex-2143611'],
 13034.0: ['nex-2192825'],
 13036.0: ['nex-2192824'],
 13050.0: ['nex-2192746'],
 13093.0: ['nex-2192742'],
 13106.0: ['nex-2192454'],
 13112.0: ['nex-2192455'],
 13121.0: ['nex-2192456'],
 13176.0: ['nex-2192459'],
 13240.0: ['nex-2179150'],
 13260.0: ['nex-2192755'],
 13294.0: ['nex-2192432'],
 13304.0: ['nex-2192429'],
 13338.0: ['nex-2167773'],
 13377.0: ['nex-2179124'],
 13400.0: ['nex-2179125'],
 13432.0: ['nex-2179131'],
 13518.0: ['nex-2167761'],
 13557.0: ['nex-2167760'],
 13583.0: ['nex-2192745'],
 13622.0: ['nex-2192416'],
 13690.0: ['nex-2167759'],
 13729.0: ['nex-2138270'],
 13753.0: ['nex-2159795'],
 13777.0: ['nex-2159223'],
 13861.0: ['nex-2159232'],
 13926.0: ['nex-2167768'],
 14541.0: ['nex-2192562'],
 14782.0: ['nex-2179128'],
 14864.0: ['nex-2179062'],
 15394.0: ['nex-2158604'],
 15497.0: ['nex-2195900'],
 15509.0: ['nex-2179059'],
 15513.0: ['nex-2167988'],
 15527.0: ['nex-2179056'],
 15537.0: ['nex-2179054'],
 15546.0: ['nex-2137104'],
 15557.0: ['nex-2167749'],
 15571.0: ['nex-2167748'],
 15573.0: ['nex-2167747'],
 15581.0: ['nex-2167744'],
 15599.0: ['nex-2167743'],
 15609.0: ['nex-2195131'],
 15615.0: ['nex-2167732'],
 15636.0: ['nex-2167728'],
 15638.0: ['nex-2140918'],
 15648.0: ['nex-2140882'],
 15651.0: ['nex-2137460'],
 15678.0: ['nex-2137618'],
 15681.0: ['nex-2167731'],
 15692.0: ['nex-2158863'],
 15709.0: ['nex-2153374'],
 15719.0: ['nex-2178929'],
 15772.0: ['nex-2178764'],
 15781.0: ['nex-2178635'],
 15782.0: ['nex-2179240'],
 15787.0: ['nex-2179243'],
 15811.0: ['nex-2178631'],
 15824.0: ['nex-2178634'],
 15840.0: ['nex-2178632'],
 15871.0: ['nex-2140888'],
 15914.0: ['nex-2167769'],
 15919.0: ['nex-2178495'],
 15952.0: ['nex-2167775'],
 15966.0: ['nex-2179259'],
 15985.0: ['nex-2179402'],
 15992.0: ['nex-2179403'],
 16042.0: ['nex-2179246'],
 16071.0: ['nex-2178928'],
 16116.0: ['nex-2179241'],
 16144.0: ['nex-2140894'],
 16150.0: ['nex-2179239'],
 16164.0: ['nex-2167735'],
 16185.0: ['nex-2178834'],
 16281.0: ['nex-2189682'],
 16367.0: ['nex-2167723'],
 16394.0: ['nex-2167721'],
 16428.0: ['nex-2167724'],
 16575.0: ['nex-2158537'],
 16586.0: ['nex-2179332'],
 16677.0: ['nex-2181285'],
 16852.0: ['nex-2158299'],
 16865.0: ['nex-2178494'],
 17000.0: ['nex-2161445'],
 17312.0: ['nex-2178630'],
 17574.0: ['nex-2178642'],
 17614.0: ['nex-2143685'],
 17804.0: ['nex-2179248'],
 17819.0: ['nex-2179258'],
 17930.0: ['nex-2179349'],
 17977.0: ['nex-2179247'],
 17981.0: ['nex-2167774'],
 17989.0: ['nex-2158198'],
 17992.0: ['nex-2158185'],
 17997.0: ['nex-2195659'],
 18015.0: ['nex-2178983'],
 18048.0: ['nex-2137108'],
 18050.0: ['nex-2179055'],
 18053.0: ['nex-2167767'],
 18060.0: ['nex-2172142'],
 18070.0: ['nex-2167374'],
 18073.0: ['nex-2146758'],
 18074.0: ['nex-2157656'],
 18083.0: ['nex-2177528'],
 18089.0: ['nex-2178538'],
 18124.0: ['nex-2179127'],
 18143.0: ['nex-2178991'],
 18162.0: ['nex-2167729'],
 18200.0: ['nex-2178836'],
 18227.0: ['nex-2178763'],
 18261.0: ['nex-2186597'],
 18269.0: ['nex-2179242'],
 18272.0: ['nex-2179251'],
 18308.0: ['nex-2179252'],
 18342.0: ['nex-2167777'],
 18347.0: ['nex-2153377'],
 18349.0: ['nex-2179610'],
 18358.0: ['nex-2167811'],
 18361.0: ['nex-2167802'],
 18396.0: ['nex-2167782'],
 18411.0: ['nex-2167793'],
 18423.0: ['nex-2179814'],
 18453.0: ['nex-2179803'],
 18474.0: ['nex-2179749'],
 18489.0: ['nex-2179666'],
 18502.0: ['nex-2179428'],
 18508.0: ['nex-2179437'],
 18521.0: ['nex-2179434'],
 18530.0: ['nex-2179429'],
 18546.0: ['nex-2179518'],
 18554.0: ['nex-2179439'],
 18566.0: ['nex-2154993'],
 18590.0: ['nex-2179576'],
 18593.0: ['nex-2178313'],
 18626.0: ['nex-2181736'],
 18636.0: ['nex-2178203'],
 18644.0: ['nex-2191594'],
 18659.0: ['nex-2178230'],
 18660.0: ['nex-2178228'],
 18665.0: ['nex-2153354'],
 18697.0: ['nex-2178227'],
 18715.0: ['nex-2167804'],
 18758.0: ['nex-2179663'],
 18761.0: ['nex-2178232'],
 18769.0: ['nex-2179430'],
 18781.0: ['nex-2179432'],
 18795.0: ['nex-2179621'],
 18818.0: ['nex-2140757'],
 18822.0: ['nex-2178410'],
 18824.0: ['nex-2178376'],
 18841.0: ['nex-2179245'],
 18895.0: ['nex-2186297'],
 18905.0: ['nex-2178184'],
 18918.0: ['nex-2178388'],
 18994.0: ['nex-2178198'],
 19041.0: ['nex-2178314'],
 19096.0: ['nex-2137274'],
 19460.0: ['nex-2179348'],
 20156.0: ['nex-2179672'],
 20268.0: ['nex-2167779'],
 20707.0: ['nex-2179753'],
 20930.0: ['nex-2179611'],
 21148.0: ['nex-2178229'],
 21647.0: ['nex-2167755'],
 21767.0: ['nex-2140891'],
 21949.0: ['nex-2171273'],
 22043.0: ['nex-2170798'],
 22061.0: ['nex-2170847'],
 22195.0: ['nex-2179436'],
 22209.0: ['nex-2179747'],
 22214.0: ['nex-2167798'],
 22239.0: ['nex-2167784'],
 22249.0: ['nex-2178360'],
 22252.0: ['nex-2177108'],
 22268.0: ['nex-2167780'],
 22282.0: ['nex-2181167'],
 22286.0: ['nex-2153426'],
 22306.0: ['nex-2138343'],
 22327.0: ['nex-2179849'],
 22346.0: ['nex-2166566'],
 22391.0: ['nex-2175816'],
 22422.0: ['nex-2180042'],
 22434.0: ['nex-2153328'],
 22444.0: ['nex-2180049'],
 22446.0: ['nex-2179843'],
 22667.0: ['nex-2180048'],
 22849.0: ['nex-2167485'],
 22981.0: ['nex-2180047'],
 23030.0: ['nex-2179842'],
 23149.0: ['nex-2179838'],
 23182.0: ['nex-2179853'],
 23283.0: ['nex-2179836'],
 23291.0: ['nex-2179833'],
 23309.0: ['nex-2180140'],
 23317.0: ['nex-2138341'],
 23352.0: ['nex-2138332'],
 23421.0: ['nex-2179835'],
 23425.0: ['nex-2146593'],
 23435.0: ['nex-2179839'],
 23472.0: ['nex-2178022'],
 23482.0: ['nex-2178021'],
 23499.0: ['nex-2178102'],
 23512.0: ['nex-2178101'],
 23527.0: ['nex-2178096'],
 23542.0: ['nex-2178100'],
 23569.0: ['nex-2138335'],
 23594.0: ['nex-2178025'],
 23632.0: ['nex-2178074'],
 23638.0: ['nex-2178095'],
 23659.0: ['nex-2178017'],
 23683.0: ['nex-2178026'],
 23742.0: ['nex-2191456'],
 23744.0: ['nex-2164642'],
 23763.0: ['nex-2137004'],
 23782.0: ['nex-2178139'],
 23800.0: ['nex-2142314'],
 23845.0: ['nex-2178099'],
 23893.0: ['nex-2178019'],
 23934.0: ['nex-2153384'],
 23990.0: ['nex-2179917'],
 24056.0: ['nex-2179931'],
 24200.0: ['nex-2178140'],
 24569.0: ['nex-2178016'],
 24904.0: ['nex-2145415'],
 25099.0: ['nex-2138334'],
 25107.0: ['nex-2167843'],
 25108.0: ['nex-2177620'],
 25116.0: ['nex-2178018'],
 25129.0: ['nex-2167841'],
 25131.0: ['nex-2167844'],
 25147.0: ['nex-2167836'],
 25154.0: ['nex-2167833'],
 25163.0: ['nex-2167820'],
 25179.0: ['nex-2180186'],
 25191.0: ['nex-2180169'],
 25196.0: ['nex-2180167'],
 25206.0: ['nex-2167823'],
 25221.0: ['nex-2180205'],
 25228.0: ['nex-2167835'],
 25277.0: ['nex-2177221'],
 25289.0: ['nex-2177155'],
 25292.0: ['nex-2177107'],
 25309.0: ['nex-2177157'],
 25317.0: ['nex-2177153'],
 25322.0: ['nex-2159303'],
 25323.0: ['nex-2177150'],
 25344.0: ['nex-2177147'],
 25349.0: ['nex-2177088'],
 25351.0: ['nex-2180187'],
 25361.0: ['nex-2177086'],
 25381.0: ['nex-2167839'],
 25407.0: ['nex-2167824'],
 25424.0: ['nex-2177115'],
 25535.0: ['nex-2177152'],
 25591.0: ['nex-2180188'],
 26224.0: ['nex-2161080'],
 26404.0: ['nex-2177072'],
 26899.0: ['nex-2167831'],
 26975.0: ['nex-2138442'],
 26980.0: ['nex-2177550'],
 26986.0: ['nex-2177547'],
 27014.0: ['nex-2177536'],
 27066.0: ['nex-2177947'],
 27095.0: ['nex-2177636'],
 27118.0: ['nex-2177623'],
 27125.0: ['nex-2167812'],
 27141.0: ['nex-2177690'],
 27161.0: ['nex-2177291'],
 27192.0: ['nex-2177560'],
 27228.0: ['nex-2177530'],
 27231.0: ['nex-2164546'],
 27258.0: ['nex-2177629'],
 27284.0: ['nex-2177554'],
 27286.0: ['nex-2167797'],
 27302.0: ['nex-2177985'],
 27400.0: ['nex-2177114'],
 27461.0: ['nex-2177541'],
 27639.0: ['nex-2177529'],
 27669.0: ['nex-2177524'],
 27706.0: ['nex-2177534'],
 27854.0: ['nex-2177618'],
 27916.0: ['nex-2177686'],
 28029.0: ['nex-2191458'],
 28081.0: ['nex-2177523'],
 28087.0: ['nex-2138387'],
 28099.0: ['nex-2177535'],
 28141.0: ['nex-2177548'],
 28154.0: ['nex-2177545'],
 28177.0: ['nex-2177625'],
 28194.0: ['nex-2177664'],
 28195.0: ['nex-2137320'],
 28210.0: ['nex-2177626'],
 28243.0: ['nex-2177948'],
 28276.0: ['nex-2177886'],
 28295.0: ['nex-2177622'],
 28367.0: ['nex-2177539'],
 28377.0: ['nex-2177582'],
 28399.0: ['nex-2177533'],
 28923.0: ['nex-2177949'],
 28940.0: ['nex-2158984'],
 28985.0: ['nex-2177546'],
 29030.0: ['nex-2177663'],
 29036.0: ['nex-2177788'],
 29051.0: ['nex-2137395'],
 29084.0: ['nex-2137327'],
 29090.0: ['nex-2177631'],
 29102.0: ['nex-2177787'],
 29103.0: ['nex-2195178'],
 29154.0: ['nex-2177637'],
 29168.0: ['nex-2177692'],
 29184.0: ['nex-2177555'],
 29203.0: ['nex-2177280'],
 29212.0: ['nex-2177476'],
 29256.0: ['nex-2177274'],
 29271.0: ['nex-2177271'],
 29283.0: ['nex-2177267'],
 29292.0: ['nex-2177450'],
 29316.0: ['nex-2177264'],
 29358.0: ['nex-2177254'],
 29359.0: ['nex-2177251'],
 29375.0: ['nex-2177245'],
 29389.0: ['nex-2177243'],
 29397.0: ['nex-2177278'],
 29433.0: ['nex-2177258'],
 29447.0: ['nex-2177382'],
 29467.0: ['nex-2145416'],
 29472.0: ['nex-2177335'],
 29536.0: ['nex-2177255'],
 29632.0: ['nex-2177277'],
 29660.0: ['nex-2176852'],
 29701.0: ['nex-2177501'],
 29825.0: ['nex-2177242'],
 29832.0: ['nex-2177246'],
 29881.0: ['nex-2177259'],
 30085.0: ['nex-2177685'],

In [1]:
import geopandas as gpd

df_v3 = gpd.list_layers("/home/quinn/Contribute_troute/v3/ngen-v3-nwis-03366500.gpkg")

In [2]:
df_v3

                  name    geometry_type
0                nexus            Point
1            flowpaths  MultiLineString
2              divides          Polygon
3            flowlines  MultiLineString
4    incremental_areas          Polygon
5                 pois            Point
6              network             None
7  flowpath-attributes             None
8  flowline-attributes             None
9    divide-attributes             None

In [3]:
df_v3_fl = gpd.read_file("/home/quinn/Contribute_troute/v3/ngen-v3-nwis-03366500.gpkg", layer = "flowlines")

In [4]:
df_v3_fl_attr = gpd.read_file("/home/quinn/Contribute_troute/v3/ngen-v3-nwis-03366500.gpkg", layer = "flowline-attributes")

In [5]:
df_v3_fl

,flowline_id,flowline_toid,flowline_incr,flowline_hydroseq,areasqkm,area_ratio,flowpath_id,flowpath_toid,incremental_area_id,reference_id,vpuid,geometry
0,505428,505371,1.0,655345,3.416400,0.750,fp-12,nex-11,505428,18450877,05,"MULTILINESTRING ((901410.469 1788122.186, 9014..."
1,488259,505428,2.0,655346,1.140750,0.250,fp-12,nex-11,488259,25168673,05,"MULTILINESTRING ((901087.409 1788021.307, 9014..."
2,505533,505513,1.0,655395,1.870650,0.731,fp-14,nex-13,505533,18450579,05,"MULTILINESTRING ((889849.865 1806804.805, 8897..."
3,505540,505533,3.0,655401,0.546750,0.214,fp-14,nex-13,505540,18450561,05,"MULTILINESTRING ((889644.672 1807383.567, 8896..."
4,505539,505533,2.0,655400,0.140850,0.055,fp-14,nex-13,505539,18450563,05,"MULTILINESTRING ((889724.728 1807258.032, 8897..."
...,...,...,...,...,...,...,...,...,...,...,...,...
120,616415,616416,1.0,655436,8.913479,1.000,fp-29,nex-28,616415,18450015.1,05,"MULTILINESTRING ((912636.434 1829516.547, 9124..."
121,505645,616415,1.0,655437,28.150200,1.000,fp-38,nex-29,505645,18449999,05,"MULTILINESTRING ((914051.805 1834163.478, 9139..."
122,614145,616415,1.0,655438,11.530235,1.000,fp-30,nex-29,614145,18450005.2,05,"MULTILINESTRING ((916779.986 1830769.054, 9167..."
123,614144,614145,1.0,655439,22.253515,1.000,fp-31,nex-30,614144,18450005.1,05,"MULTILINESTRING ((919444.103 1831870.205, 9193..."
124,616390,616391,1.0,655440,9.453186,1.000,fp-34,nex-33,616390,18450443.1,05,"MULTILINESTRING ((895539.804 1819032.127, 8954..."

In [6]:
df_v3_fl_attr

,flowline_id,lengthm,BtmWdth,TopWdth,ChSlp,n,nCC,So,TopWdthCC,hl_reference,MusX,MusK
0,505645.0,7672.800516,6.601679,16.222368,3.607050,0.229953,0.459905,0.003215,48.667105,,0.2,3600.0
1,616416.0,1063.720438,12.148260,22.460106,3.286514,0.217988,0.435975,0.001507,67.380318,,0.2,3600.0
2,616415.0,3296.535186,12.148260,22.460106,3.286514,0.217988,0.435975,0.001507,67.380318,,0.2,3600.0
3,616401.0,2838.142855,18.223806,28.499531,2.834587,0.269787,0.539574,0.001810,85.498592,,0.2,3600.0
4,616400.0,7883.775118,18.223806,28.499531,2.834587,0.269787,0.539574,0.001810,85.498592,,0.2,3600.0
...,...,...,...,...,...,...,...,...,...,...,...,...
120,505621.0,3791.028149,7.523001,15.936501,2.650889,0.264468,0.528936,0.001580,47.809502,,0.2,3600.0
121,505638.0,3097.673265,4.320529,14.096350,4.029885,0.247089,0.494179,0.004460,42.289049,,0.2,3600.0
122,505636.0,3811.658546,14.752187,26.012577,3.262331,0.192605,0.385211,0.001697,78.037731,,0.2,3600.0
123,614145.0,5705.806419,8.197044,17.373981,3.155725,0.166084,0.332169,0.002573,52.121944,,0.2,3600.0
124,614144.0,5705.806419,8.197044,17.373981,3.155725,0.166084,0.332169,0.002573,52.121944,,0.2,3600.0

In [7]:
df_v3_fl_attr.rename(columns={'flowline_id': 'id'}, inplace=True)
df_v3_fl.rename(columns={'flowline_id': 'id'}, inplace=True)

In [8]:
df_v3_fl

,id,flowline_toid,flowline_incr,flowline_hydroseq,areasqkm,area_ratio,flowpath_id,flowpath_toid,incremental_area_id,reference_id,vpuid,geometry
0,505428,505371,1.0,655345,3.416400,0.750,fp-12,nex-11,505428,18450877,05,"MULTILINESTRING ((901410.469 1788122.186, 9014..."
1,488259,505428,2.0,655346,1.140750,0.250,fp-12,nex-11,488259,25168673,05,"MULTILINESTRING ((901087.409 1788021.307, 9014..."
2,505533,505513,1.0,655395,1.870650,0.731,fp-14,nex-13,505533,18450579,05,"MULTILINESTRING ((889849.865 1806804.805, 8897..."
3,505540,505533,3.0,655401,0.546750,0.214,fp-14,nex-13,505540,18450561,05,"MULTILINESTRING ((889644.672 1807383.567, 8896..."
4,505539,505533,2.0,655400,0.140850,0.055,fp-14,nex-13,505539,18450563,05,"MULTILINESTRING ((889724.728 1807258.032, 8897..."
...,...,...,...,...,...,...,...,...,...,...,...,...
120,616415,616416,1.0,655436,8.913479,1.000,fp-29,nex-28,616415,18450015.1,05,"MULTILINESTRING ((912636.434 1829516.547, 9124..."
121,505645,616415,1.0,655437,28.150200,1.000,fp-38,nex-29,505645,18449999,05,"MULTILINESTRING ((914051.805 1834163.478, 9139..."
122,614145,616415,1.0,655438,11.530235,1.000,fp-30,nex-29,614145,18450005.2,05,"MULTILINESTRING ((916779.986 1830769.054, 9167..."
123,614144,614145,1.0,655439,22.253515,1.000,fp-31,nex-30,614144,18450005.1,05,"MULTILINESTRING ((919444.103 1831870.205, 9193..."
124,616390,616391,1.0,655440,9.453186,1.000,fp-34,nex-33,616390,18450443.1,05,"MULTILINESTRING ((895539.804 1819032.127, 8954..."

In [9]:
unique_cols = set(df_v3_fl_attr.columns).difference(set(df_v3_fl.columns))

In [10]:
unique_cols.add("id")

In [11]:
unique_cols

{'BtmWdth',
 'ChSlp',
 'MusK',
 'MusX',
 'So',
 'TopWdth',
 'TopWdthCC',
 'hl_reference',
 'id',
 'lengthm',
 'n',
 'nCC'}

In [12]:
import pandas as pd
df_v3_fl_attr = df_v3_fl_attr[list(unique_cols)]
flowlines = pd.merge(
    df_v3_fl, 
    df_v3_fl_attr, 
    on='id', 
    how='inner'
)

In [13]:
flowlines.columns

Index(['id', 'flowline_toid', 'flowline_incr', 'flowline_hydroseq', 'areasqkm',
       'area_ratio', 'flowpath_id', 'flowpath_toid', 'incremental_area_id',
       'reference_id', 'vpuid', 'geometry', 'MusK', 'nCC', 'hl_reference',
       'MusX', 'n', 'ChSlp', 'BtmWdth', 'TopWdth', 'TopWdthCC', 'So',
       'lengthm'],
      dtype='object')

In [14]:
s = flowlines['hl_reference'].fillna('').str.extract(r'(?:^|,)\s*nwis-(\d{8})', expand=True)[0]

In [15]:
df_flowpath = gpd.read_file("/home/quinn/Contribute_troute/v3/ngen-v3-nwis-03366500.gpkg", layer = "flowpaths")

In [16]:
df_flowpath

,flowpath_id,flowpath_toid,flowline_id,mainstem,member_comid,poi_id,hydroseq,lengthkm,areasqkm,tot_drainage_areasqkm,has_divide,divide_id,geometry
0,fp-12,nex-11,"505428,488259",111926,"18450877,25168673",None,94,1.511748,4.557150,4.557150,True,cat-12,"MULTILINESTRING ((901087.409 1788021.307, 9014..."
1,fp-14,nex-13,"505533,505540,505539",112222,"18450579,18450561,18450563",None,4,3.112408,2.558250,257.167800,True,cat-14,"MULTILINESTRING ((889644.672 1807383.567, 8896..."
2,fp-32,nex-17,"505567,505357",112228,"18450497,18451119,18450493",None,15,4.424542,6.374250,6.374250,True,cat-32,"MULTILINESTRING ((894801.504 1812461.686, 8947..."
3,fp-35,nex-20,"505583,488256",112235,"18450447,25168685,18450445",None,20,3.640681,4.219649,4.219649,True,cat-35,"MULTILINESTRING ((897274.171 1815723.801, 8969..."
4,fp-36,nex-24,"505609,505635",112241,"18450373,18450025",None,26,4.497157,9.508051,9.508051,True,cat-36,"MULTILINESTRING ((902456.509 1825444.106, 9024..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,fp-29,nex-28,616415,112222,18450015.1,145027,31,3.296535,8.913479,70.847429,True,cat-29,"MULTILINESTRING ((912636.434 1829516.547, 9124..."
95,fp-38,nex-29,505645,112250,18449999,145025,33,7.672801,28.150200,28.150200,True,cat-38,"MULTILINESTRING ((914051.805 1834163.478, 9139..."
96,fp-30,nex-29,614145,112222,18450005.2,None,32,5.705806,11.530235,33.783750,True,cat-30,"MULTILINESTRING ((916779.986 1830769.054, 9167..."
97,fp-31,nex-30,614144,112222,18450005.1,None,34,5.705806,22.253515,22.253515,True,cat-31,"MULTILINESTRING ((919444.103 1831870.205, 9193..."
98,fp-34,nex-33,616390,112232,18450443.1,145047,41,5.419181,9.453186,9.453186,True,cat-34,"MULTILINESTRING ((895539.804 1819032.127, 8954..."

In [17]:
df_flowpath[['flowpath_id', 'mainstem']]

   flowpath_id  mainstem
0        fp-12    111926
1        fp-14    112222
2        fp-32    112228
3        fp-35    112235
4        fp-36    112241
..         ...       ...
94       fp-29    112222
95       fp-38    112250
96       fp-30    112222
97       fp-31    112222
98       fp-34    112232

[99 rows x 2 columns]

In [18]:
flowlines = pd.merge(flowlines, df_flowpath[['flowpath_id', 'mainstem']], on = 'flowpath_id', how = 'outer')

In [19]:
flowlines

,id,flowline_toid,flowline_incr,flowline_hydroseq,areasqkm,area_ratio,flowpath_id,flowpath_toid,incremental_area_id,reference_id,...,hl_reference,MusX,n,ChSlp,BtmWdth,TopWdth,TopWdthCC,So,lengthm,mainstem
0,616334,505514,1.0,655312,4.200862,1.0,fp-1,nex-0,616334,18451023.2,...,"nwis-03366500,lid-DEPI3",0.2,0.095697,3.391069,23.946900,38.801624,116.404873,0.000010,3051.809159,111926
1,505383,505473,1.0,655340,6.943050,1.0,fp-10,nex-9,505383,"18451039,18450747",...,,0.2,0.166579,2.732921,15.025311,23.186830,69.560490,0.001863,3682.794404,111926
2,505465,505361,1.0,655327,4.736251,1.0,fp-100,nex-99,505465,18450771,...,,0.2,0.323701,3.842345,4.150549,12.121985,36.365956,0.008733,2905.964414,112337
3,505490,505493,1.0,655323,2.262150,0.5,fp-101,nex-97,505490,18450693,...,,0.2,0.351436,3.358251,3.685742,11.026401,33.079203,0.008099,2490.149893,112338
4,505488,505490,2.0,655328,2.259000,0.5,fp-101,nex-97,505488,18450697,...,,0.2,0.351436,3.358251,3.685742,11.026401,33.079203,0.008099,1941.509367,112338
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,505386,505473,1.0,655341,7.581600,1.0,fp-95,nex-9,505386,18451033,...,,0.2,0.301228,3.186192,7.201943,14.492872,43.478617,0.006108,5671.299580,112335
121,505487,505386,1.0,655353,5.338350,1.0,fp-96,nex-95,505487,18450699,...,,0.2,0.343920,3.361297,5.433115,12.456465,37.369394,0.004693,2721.909543,112335
122,505493,505509,1.0,655320,4.702500,1.0,fp-97,nex-3,505493,18450683,...,,0.2,0.114550,1.672479,14.952971,19.524281,58.572842,0.002741,3932.612053,112337
123,505482,505493,1.0,655322,3.383099,1.0,fp-98,nex-97,505482,18450719,...,,0.2,0.198149,2.950316,9.142278,18.393745,55.181236,0.002392,2754.805582,112337
124,505361,505482,1.0,655324,17.299350,1.0,fp-99,nex-98,505361,18451109,...,,0.2,0.278496,2.872692,6.555185,14.837358,44.512073,0.002989,5452.626766,112337

In [20]:
def numeric_id(flowpath, id_col='key', toid_col='downstream'):
    id = flowpath[id_col].split('-')[-1]
    toid = flowpath[toid_col].split('-')[-1]
    flowpath[id_col] = int(float(id))
    flowpath[toid_col] = int(float(toid))
    return flowpath

flowlines2 = flowlines.apply(numeric_id, axis=1, args=('flowpath_id', 'flowpath_toid'))
flowlines2

,id,flowline_toid,flowline_incr,flowline_hydroseq,areasqkm,area_ratio,flowpath_id,flowpath_toid,incremental_area_id,reference_id,...,hl_reference,MusX,n,ChSlp,BtmWdth,TopWdth,TopWdthCC,So,lengthm,mainstem
0,616334,505514,1.0,655312,4.200862,1.0,1,0,616334,18451023.2,...,"nwis-03366500,lid-DEPI3",0.2,0.095697,3.391069,23.946900,38.801624,116.404873,0.000010,3051.809159,111926
1,505383,505473,1.0,655340,6.943050,1.0,10,9,505383,"18451039,18450747",...,,0.2,0.166579,2.732921,15.025311,23.186830,69.560490,0.001863,3682.794404,111926
2,505465,505361,1.0,655327,4.736251,1.0,100,99,505465,18450771,...,,0.2,0.323701,3.842345,4.150549,12.121985,36.365956,0.008733,2905.964414,112337
3,505490,505493,1.0,655323,2.262150,0.5,101,97,505490,18450693,...,,0.2,0.351436,3.358251,3.685742,11.026401,33.079203,0.008099,2490.149893,112338
4,505488,505490,2.0,655328,2.259000,0.5,101,97,505488,18450697,...,,0.2,0.351436,3.358251,3.685742,11.026401,33.079203,0.008099,1941.509367,112338
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,505386,505473,1.0,655341,7.581600,1.0,95,9,505386,18451033,...,,0.2,0.301228,3.186192,7.201943,14.492872,43.478617,0.006108,5671.299580,112335
121,505487,505386,1.0,655353,5.338350,1.0,96,95,505487,18450699,...,,0.2,0.343920,3.361297,5.433115,12.456465,37.369394,0.004693,2721.909543,112335
122,505493,505509,1.0,655320,4.702500,1.0,97,3,505493,18450683,...,,0.2,0.114550,1.672479,14.952971,19.524281,58.572842,0.002741,3932.612053,112337
123,505482,505493,1.0,655322,3.383099,1.0,98,97,505482,18450719,...,,0.2,0.198149,2.950316,9.142278,18.393745,55.181236,0.002392,2754.805582,112337
124,505361,505482,1.0,655324,17.299350,1.0,99,98,505361,18451109,...,,0.2,0.278496,2.872692,6.555185,14.837358,44.512073,0.002989,5452.626766,112337

In [21]:
key_nums =  set(flowlines2.flowpath_id)
down_nums = set(flowlines2.flowpath_toid)
print(key_nums)
print(down_nums)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 46, 47, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102}
{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 33, 39, 40, 41, 42, 43, 49, 50, 51, 54, 57, 59, 60, 61, 62, 63, 64, 65, 66, 67, 69, 70, 71, 75, 76, 78, 79, 84, 88, 89, 92, 95, 97, 98, 99}

In [22]:
df_flowpath_attr = gpd.read_file("/home/quinn/Contribute_troute/v3/ngen-v3-nwis-03366500.gpkg", layer = "flowpath-attributes")

In [23]:
df_flowpath_attr

,flowpath_id,lengthm,BtmWdth,TopWdth,ChSlp,n,nCC,So,TopWdthCC,hl_reference,MusX,MusK
0,fp-38,7672.800516,6.601679,16.222368,3.607050,0.229953,0.459905,0.003215,48.667105,,0.2,3600.0
1,fp-28,1063.720438,12.148260,22.460106,3.286514,0.217988,0.435975,0.001507,67.380318,,0.2,3600.0
2,fp-29,3296.535186,12.148260,22.460106,3.286514,0.217988,0.435975,0.001507,67.380318,,0.2,3600.0
3,fp-25,2838.142855,18.223806,28.499531,2.834587,0.269787,0.539574,0.001810,85.498592,,0.2,3600.0
4,fp-26,7883.775118,18.223806,28.499531,2.834587,0.269787,0.539574,0.001810,85.498592,,0.2,3600.0
...,...,...,...,...,...,...,...,...,...,...,...,...
94,fp-43,3791.028149,7.523001,15.936501,2.650889,0.264468,0.528936,0.001580,47.809502,,0.2,3600.0
95,fp-44,3097.673265,4.320529,14.096350,4.029885,0.247089,0.494179,0.004460,42.289049,,0.2,3600.0
96,fp-27,3811.658546,14.752187,26.012577,3.262331,0.192605,0.385211,0.001697,78.037731,,0.2,3600.0
97,fp-30,5705.806419,8.197044,17.373981,3.155725,0.166084,0.332169,0.002573,52.121944,,0.2,3600.0
98,fp-31,5705.806419,8.197044,17.373981,3.155725,0.166084,0.332169,0.002573,52.121944,,0.2,3600.0

In [24]:
flowlines.columns

Index(['id', 'flowline_toid', 'flowline_incr', 'flowline_hydroseq', 'areasqkm',
       'area_ratio', 'flowpath_id', 'flowpath_toid', 'incremental_area_id',
       'reference_id', 'vpuid', 'geometry', 'MusK', 'nCC', 'hl_reference',
       'MusX', 'n', 'ChSlp', 'BtmWdth', 'TopWdth', 'TopWdthCC', 'So',
       'lengthm', 'mainstem'],
      dtype='object')

In [25]:
flowlines.rename(columns = {'flowline_toid' : 'toid', 'lengthm' : 'Length_m'}, inplace= True)

In [26]:
flowlines.columns

Index(['id', 'toid', 'flowline_incr', 'flowline_hydroseq', 'areasqkm',
       'area_ratio', 'flowpath_id', 'flowpath_toid', 'incremental_area_id',
       'reference_id', 'vpuid', 'geometry', 'MusK', 'nCC', 'hl_reference',
       'MusX', 'n', 'ChSlp', 'BtmWdth', 'TopWdth', 'TopWdthCC', 'So',
       'Length_m', 'mainstem'],
      dtype='object')

In [27]:
dict(zip(flowlines.toid, flowlines.id))

{505514: 616334,
 505473: 505386,
 505361: 505465,
 505493: 505482,
 505490: 505488,
 505482: 505361,
 505480: 488261,
 505383: 505377,
 505371: 505428,
 505428: 488259,
 616333: 505509,
 505513: 505529,
 505533: 505539,
 505540: 616375,
 616375: 616374,
 616374: 505556,
 505557: 505567,
 616344: 616343,
 616334: 616333,
 616343: 616391,
 505404: 505583,
 616347: 616346,
 616346: 616345,
 616345: 505592,
 505602: 505609,
 616401: 616400,
 616400: 505636,
 505636: 505640,
 616416: 616415,
 616415: 505645,
 614145: 614144,
 505567: 505357,
 616391: 616390,
 505583: 488256,
 505609: 505635,
 505640: 505646,
 505592: 505596,
 505509: 505493,
 505596: 505604,
 505606: 505637,
 505637: 505621,
 505621: 505638,
 505604: 505605,
 505556: 505560,
 616367: 616366,
 505529: 505538,
 616373: 616372,
 616372: 488255,
 616366: 616363,
 505519: 614143,
 505522: 505528,
 616362: 505489,
 505501: 505520,
 505489: 505473,
 505486: 616330,
 505492: 505494,
 505500: 616338,
 505504: 505527,
 505526: 616342,
 505397: 616381,
 505564: 505565,
 616377: 616376,
 616376: 505575,
 505576: 505594,
 505595: 505619,
 616363: 616362,
 505527: 505394,
 616340: 616339,
 616339: 505542,
 505394: 505543,
 505542: 505547,
 616342: 616341,
 616341: 505580,
 616381: 616380,
 616380: 505589,
 505565: 505574,
 505575: 505586,
 616338: 616337,
 616337: 505521,
 505494: 505388,
 616330: 616329,
 616329: 505523,
 505523: 488258,
 505475: 505474,
 505377: 505466,
 505464: 505467,
 505466: 505356,
 505356: 505384,
 505386: 505487}

In [28]:
terminal_codes = set()
terminal_codes = terminal_codes | set(
            flowlines[flowlines["toid"].isin(flowlines["id"])]["toid"].values
        )

In [29]:
terminal_codes

{505356,
 505361,
 505371,
 505377,
 505383,
 505386,
 505394,
 505397,
 505404,
 505428,
 505464,
 505466,
 505473,
 505475,
 505480,
 505482,
 505486,
 505489,
 505490,
 505492,
 505493,
 505494,
 505500,
 505501,
 505504,
 505509,
 505513,
 505519,
 505522,
 505523,
 505526,
 505527,
 505529,
 505533,
 505540,
 505542,
 505556,
 505557,
 505564,
 505565,
 505567,
 505575,
 505576,
 505583,
 505592,
 505595,
 505596,
 505602,
 505604,
 505606,
 505609,
 505621,
 505636,
 505637,
 505640,
 614145,
 616329,
 616330,
 616333,
 616334,
 616337,
 616338,
 616339,
 616340,
 616341,
 616342,
 616343,
 616344,
 616345,
 616346,
 616347,
 616362,
 616363,
 616366,
 616367,
 616372,
 616373,
 616374,
 616375,
 616376,
 616377,
 616380,
 616381,
 616391,
 616400,
 616401,
 616415,
 616416}

In [30]:
import xarray as xr

ds_nwm = xr.open_dataset("~/t-route-inputs/197902101200.CHRTOUT_DOMAIN1")

In [31]:
ds_nwm

<xarray.Dataset> Size: 200MB
Dimensions:         (feature_id: 2776734, time: 1, reference_time: 1)
Coordinates:
  * time            (time) datetime64[ns] 8B 1979-02-10T12:00:00
  * reference_time  (reference_time) datetime64[ns] 8B 1979-02-01
  * feature_id      (feature_id) int64 22MB 101 179 ... 1180001803 1180001804
    latitude        (feature_id) float32 11MB ...
    longitude       (feature_id) float32 11MB ...
Data variables:
    qBtmVertRunoff  (feature_id) float64 22MB ...
    qBucket         (feature_id) float64 22MB ...
    qSfcLatRunoff   (feature_id) float64 22MB ...
    q_lateral       (feature_id) float64 22MB ...
    streamflow      (feature_id) float64 22MB ...
    velocity        (feature_id) float64 22MB ...
    crs             |S1 1B ...
    order           (feature_id) int32 11MB ...
    elevation       (feature_id) float32 11MB ...
Attributes: (12/20)
    TITLE:                      OUTPUT FROM WRF-Hydro v5.3.0-alpha1
    featureType:                timeSeries
    proj4:                      +proj=lcc +units=m +a=6370000.0 +b=6370000.0 ...
    model_initialization_time:  1979-02-01_00:00:00
    station_dimension:          feature_id
    model_output_valid_time:    1979-02-10_12:00:00
    ...                         ...
    dev_NOAH_TIMESTEP:          3600
    dev_channel_only:           0
    dev_channelBucket_only:     0
    dev:                        dev_ prefix indicates development/internal me...
    NCO:                        netCDF Operators version 5.1.4 (Homepage = ht...
    history:                    Fri Sep 15 16:41:07 2023: ncatted -O -a missi...

In [32]:
ds_nwm.feature_id.values

array([       101,        179,        181, ..., 1180001802, 1180001803,
       1180001804])

In [33]:
if 'q_lateral' in ds_nwm.variables:
    df = ds_nwm.to_dataframe().reset_index()[['feature_id', 'q_lateral']]
else:
    ds_nwm = ds_nwm.assign(q_lateral = ds_nwm['qBucket'] + ds_nwm['qSfcLatRunoff'])
    df = ds_nwm.to_dataframe().reset_index()[['feature_id', 'q_lateral']]

In [34]:
df

         feature_id  q_lateral
0               101        0.2
1               179        0.0
2               181        0.0
3               183        0.0
4               185        0.0
...             ...        ...
2776729  1180001800        0.0
2776730  1180001801        0.0
2776731  1180001802        0.0
2776732  1180001803        0.0
2776733  1180001804        0.0

[2776734 rows x 2 columns]

In [35]:
flowlines.shape

(125, 24)

In [36]:
df_new_v3 = gpd.list_layers("/home/quinn/Contribute_troute/v3/ngen-v3-nwis-02299950_v2.gpkg")

In [37]:
df_new_v3

                   name    geometry_type
0                 nexus            Point
1             flowpaths  MultiLineString
2               divides          Polygon
3             flowlines  MultiLineString
4     incremental_areas          Polygon
5                  pois            Point
6               network             None
7   flowpath-attributes             None
8   flowline-attributes             None
9     divide-attributes             None
10          network_mod             None

In [38]:
df_new_v3_fl = gpd.read_file("/home/quinn/Contribute_troute/v3/ngen-v3-nwis-02299950_v2.gpkg", layer = "flowlines")
df_new_v3_nexus = gpd.read_file("/home/quinn/Contribute_troute/v3/ngen-v3-nwis-02299950_v2.gpkg", layer = "nexus")
df_new_v3_fl_attr = gpd.read_file("/home/quinn/Contribute_troute/v3/ngen-v3-nwis-02299950_v2.gpkg", layer = "flowline-attributes")
df_new_v3_network_mod = gpd.read_file("/home/quinn/Contribute_troute/v3/ngen-v3-nwis-02299950_v2.gpkg", layer = "network_mod")

In [39]:
df_new_v3_network_mod

,nexus_id,ds_flowline,flowpath_id,flowpath_lengthkm,hydroseq,divide_id,flowline_id,flowline_toid,flowline_hydroseq,flowline_lengthkm,incremental_area_id,incremental_areasqkm,poi_id,hl_reference,hl_class,hl_source,hl_uri,reference_id,areasqkm,tot_drainage_areasqkm
0,nex-0,233551,fp-1,1.814983,23.0,cat-1,233551.0,233549.0,233936.0,1.814983,233551.0,2.585701,134129,nwis-02299950,gage,USGS,https://waterdata.usgs.gov/monitoring-location...,16877194.0,5.16825,181.974600
1,nex-0,233551,fp-1,1.814983,23.0,cat-1,233551.0,233549.0,233936.0,1.814983,233551.0,2.585701,134129,nwis-02299950,gage,USGS,https://waterdata.usgs.gov/monitoring-location...,16877108.0,5.16825,181.974600
2,nex-0,233551,fp-1,1.814983,23.0,cat-1,233567.0,233551.0,233940.0,1.567711,233567.0,2.582549,134129,nwis-02299950,gage,USGS,https://waterdata.usgs.gov/monitoring-location...,16877194.0,5.16825,181.974600
3,nex-0,233551,fp-1,1.814983,23.0,cat-1,233567.0,233551.0,233940.0,1.567711,233567.0,2.582549,134129,nwis-02299950,gage,USGS,https://waterdata.usgs.gov/monitoring-location...,16877108.0,5.16825,181.974600
4,nex-0,233551,fp-1,1.814983,23.0,cat-1,233551.0,233549.0,233936.0,1.814983,233551.0,2.585701,134129,lid-MKHF1,gage,NWS,https://water.noaa.gov/gauges/MKHF1,16877194.0,5.16825,181.974600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,nex-8,233590,fp-9,2.462047,14.0,cat-9,233599.0,233594.0,233948.0,1.105151,233599.0,2.070450,None,None,None,None,None,16876968.0,3.55995,70.503301
89,nex-8,233590,fp-9,2.462047,14.0,cat-9,233599.0,233594.0,233948.0,1.105151,233599.0,2.070450,None,None,None,None,None,16876904.0,3.55995,70.503301
90,nex-9,233594,fp-14,2.935931,16.0,cat-14,233600.0,233594.0,233949.0,2.935931,233600.0,4.781700,None,None,None,None,None,16876902.0,4.78170,4.781700
91,nex-9,233594,fp-14,2.935931,16.0,cat-14,233600.0,233594.0,233949.0,2.935931,233600.0,4.781700,None,None,None,None,None,16875380.0,4.78170,4.781700
92,nex-9,233594,fp-10,2.456318,15.0,cat-10,233647.0,233599.0,233950.0,2.456318,233647.0,6.653250,None,None,None,None,None,16875608.0,6.65325,62.161650

In [40]:
df_new_v3_network_mod[df_new_v3_network_mod['nexus_id'] == 'nex-8']

,nexus_id,ds_flowline,flowpath_id,flowpath_lengthkm,hydroseq,divide_id,flowline_id,flowline_toid,flowline_hydroseq,flowline_lengthkm,incremental_area_id,incremental_areasqkm,poi_id,hl_reference,hl_class,hl_source,hl_uri,reference_id,areasqkm,tot_drainage_areasqkm
86,nex-8,233590,fp-9,2.462047,14.0,cat-9,233594.0,233590.0,233947.0,1.356896,233594.0,1.48950,None,None,None,None,None,16876968.0,3.55995,70.503301
87,nex-8,233590,fp-9,2.462047,14.0,cat-9,233594.0,233590.0,233947.0,1.356896,233594.0,1.48950,None,None,None,None,None,16876904.0,3.55995,70.503301
88,nex-8,233590,fp-9,2.462047,14.0,cat-9,233599.0,233594.0,233948.0,1.105151,233599.0,2.07045,None,None,None,None,None,16876968.0,3.55995,70.503301
89,nex-8,233590,fp-9,2.462047,14.0,cat-9,233599.0,233594.0,233948.0,1.105151,233599.0,2.07045,None,None,None,None,None,16876904.0,3.55995,70.503301

In [41]:
#remove duplicate 'nexus_id's and reindex
df_new_v3_network_mod['nexus_id'].value_counts()
df_new_v3_network_mod = df_new_v3_network_mod.drop_duplicates(subset=['nexus_id']).reset_index(drop=True)

In [42]:
df_new_v3_network_mod

,nexus_id,ds_flowline,flowpath_id,flowpath_lengthkm,hydroseq,divide_id,flowline_id,flowline_toid,flowline_hydroseq,flowline_lengthkm,incremental_area_id,incremental_areasqkm,poi_id,hl_reference,hl_class,hl_source,hl_uri,reference_id,areasqkm,tot_drainage_areasqkm
0,nex-0,233551,fp-1,1.814983,23.0,cat-1,233551.0,233549.0,233936.0,1.814983,233551.0,2.585701,134129,nwis-02299950,gage,USGS,https://waterdata.usgs.gov/monitoring-location...,16877194.0,5.168250,181.974600
1,nex-1,233551,fp-2,2.043445,1.0,cat-2,233566.0,233551.0,233939.0,2.043445,233566.0,2.999250,None,None,None,None,None,16877110.0,2.999250,176.806350
2,nex-10,233647,fp-18,3.438158,19.0,cat-18,233652.0,233647.0,233951.0,3.438158,233652.0,4.346100,None,None,None,None,None,16875594.0,4.346100,4.346100
3,nex-11,233654,fp-12,3.669163,20.0,cat-12,229940.0,233654.0,233954.0,1.115559,229940.0,2.045700,None,None,None,None,None,27682987.0,9.548550,25.690050
4,nex-12,233707,fp-16,3.116706,22.0,cat-16,233718.0,233707.0,233957.0,3.116706,233718.0,3.554550,None,None,None,None,None,16875090.0,3.554550,3.554550
5,nex-2,233566,fp-3,1.016281,2.0,cat-3,233579.0,233566.0,233942.0,1.016281,233579.0,1.568250,134117,huc12-031002020101,watershed,USGS,https://api.water.usgs.gov/nldi/linked-data/hu...,16877052.0,1.568250,164.151000
6,nex-20,233695,fp-24,4.473559,11.0,cat-24,233664.0,233695.0,233966.0,4.473559,233664.0,6.330599,None,None,None,None,None,16875560.0,6.330599,6.330599
7,nex-3,233579,fp-8,1.686625,6.0,cat-8,233590.0,233579.0,233945.0,1.686625,233590.0,2.412000,134115,huc12-031002020102,watershed,USGS,https://api.water.usgs.gov/nldi/linked-data/hu...,16876984.0,3.722400,74.225701
8,nex-4,233648,fp-5,8.828803,7.0,cat-5,233645.0,233688.0,233964.0,8.252757,233645.0,14.936400,None,None,None,None,None,16875620.0,21.631949,49.126949
9,nex-5,233645,fp-26,3.081101,13.0,cat-26,233728.0,233645.0,233971.0,3.081101,233728.0,3.124800,None,None,None,None,None,16875062.0,3.124800,3.124800
10,nex-8,233590,fp-9,2.462047,14.0,cat-9,233594.0,233590.0,233947.0,1.356896,233594.0,1.489500,None,None,None,None,None,16876968.0,3.559950,70.503301
11,nex-9,233594,fp-14,2.935931,16.0,cat-14,233600.0,233594.0,233949.0,2.935931,233600.0,4.781700,None,None,None,None,None,16876902.0,4.781700,4.781700

In [43]:
df_new_v3_nexus

   nexus_id nexus_toid                        geometry
0     nex-8       fp-8  POINT (1367801.952 591503.549)
1    nex-11      fp-11  POINT (1374862.565 598436.525)
2     nex-0       fp-0    POINT (1363929.5 587809.512)
3     nex-1       fp-1   POINT (1364721.298 589165.06)
4     nex-2       fp-2   POINT (1365740.56 590342.013)
5     nex-2       fp-2   POINT (1365307.036 590886.49)
6     nex-3       fp-3  POINT (1366256.353 591046.423)
7     nex-9       fp-9   POINT (1368816.202 592345.17)
8    nex-10      fp-10  POINT (1371024.915 594687.666)
9    nex-10      fp-10  POINT (1371024.915 594687.666)
10   nex-12      fp-12  POINT (1375229.585 600466.288)
11    nex-4       fp-4  POINT (1366599.503 594847.455)
12   nex-20      fp-20  POINT (1367007.384 597164.017)
13    nex-5       fp-5  POINT (1370497.573 601239.908)

In [44]:
df_new_v3_fl

,flowline_id,flowline_toid,flowline_incr,flowline_hydroseq,areasqkm,area_ratio,flowpath_id,flowpath_toid,incremental_area_id,reference_id,vpuid,geometry
0,233589,233579,1.0,233944,1.360799,0.150,fp-4,nex-3,233589,16876986,03S,"MULTILINESTRING ((1366200.124 592249.188, 1366..."
1,233648,233589,2.0,233960,6.705451,0.741,fp-4,nex-3,233648,16875606,03S,"MULTILINESTRING ((1366599.503 594847.455, 1366..."
2,233688,233648,3.0,233963,0.983700,0.109,fp-4,nex-3,233688,16875204,03S,"MULTILINESTRING ((1367016.51 595767.402, 13669..."
3,233645,233688,1.0,233964,14.936400,0.690,fp-5,nex-4,233645,16875620,03S,"MULTILINESTRING ((1370497.573 601239.908, 1370..."
4,233729,233645,2.0,233972,5.635800,0.261,fp-5,nex-4,233729,16875060,03S,"MULTILINESTRING ((1370718.87 601735.095, 13707..."
5,233666,233729,3.0,233973,1.059750,0.049,fp-5,nex-4,233666,16875546,03S,"MULTILINESTRING ((1370286.357 602271.874, 1370..."
6,233594,233590,1.0,233947,1.489500,0.418,fp-9,nex-8,233594,16876968,03S,"MULTILINESTRING ((1368816.202 592345.17, 13687..."
7,233599,233594,2.0,233948,2.070450,0.582,fp-9,nex-8,233599,16876904,03S,"MULTILINESTRING ((1369792.153 592774.959, 1369..."
8,229940,233654,1.0,233954,2.045700,0.214,fp-12,nex-11,229940,27682987,03S,"MULTILINESTRING ((1375065.843 599299.665, 1374..."
9,233707,229940,2.0,233956,6.936750,0.726,fp-12,nex-11,233707,16875124,03S,"MULTILINESTRING ((1375229.585 600466.288, 1375..."
10,233719,233707,3.0,233958,0.566100,0.059,fp-12,nex-11,233719,16875088,03S,"MULTILINESTRING ((1375252.936 601499.807, 1375..."
11,233695,233688,1.0,233965,1.645200,0.169,fp-20,nex-4,233695,16875172,03S,"MULTILINESTRING ((1367007.384 597164.017, 1367..."
12,233705,233695,2.0,233967,5.754150,0.590,fp-20,nex-4,233705,16875136,03S,"MULTILINESTRING ((1365640.398 597354.215, 1365..."
13,233662,233705,3.0,233968,2.345400,0.241,fp-20,nex-4,233662,"16875564,16875134",03S,"MULTILINESTRING ((1363902.42 597119.42, 136398..."
14,233551,233549,1.0,233936,2.585701,0.500,fp-1,nex-0,233551,16877194,03S,"MULTILINESTRING ((1364721.298 589165.06, 13647..."
15,233567,233551,2.0,233940,2.582549,0.500,fp-1,nex-0,233567,16877108,03S,"MULTILINESTRING ((1363374.584 589813.053, 1363..."
16,233566,233551,1.0,233939,2.999250,1.000,fp-2,nex-1,233566,16877110,03S,"MULTILINESTRING ((1365740.56 590342.013, 13657..."
17,233578,233566,1.0,233941,5.770349,1.000,fp-29,nex-2,233578,"16877054,16876988",03S,"MULTILINESTRING ((1364533.928 591950.946, 1364..."
18,233579,233566,1.0,233942,1.568250,1.000,fp-3,nex-2,233579,16877052,03S,"MULTILINESTRING ((1366256.353 591046.423, 1366..."
19,233588,233566,1.0,233943,3.885751,1.000,fp-30,nex-2,233588,16876990,03S,"MULTILINESTRING ((1364034.709 591116.105, 1364..."
20,233590,233579,1.0,233945,2.412000,0.648,fp-8,nex-3,233590,16876984,03S,"MULTILINESTRING ((1367801.952 591503.549, 1367..."
21,233583,233590,2.0,233946,1.310400,0.352,fp-8,nex-3,233583,16877030,03S,"MULTILINESTRING ((1368401.625 590934.957, 1368..."
22,233600,233594,1.0,233949,4.781700,1.000,fp-14,nex-9,233600,"16876902,16875380",03S,"MULTILINESTRING ((1368283.752 594974.789, 1368..."
23,233647,233599,1.0,233950,6.653250,1.000,fp-10,nex-9,233647,16875608,03S,"MULTILINESTRING ((1371024.915 594687.666, 1370..."
24,233652,233647,1.0,233951,4.346100,1.000,fp-18,nex-10,233652,16875594,03S,"MULTILINESTRING ((1374198.336 594497.523, 1374..."
25,233653,233647,1.0,233952,7.701300,1.000,fp-17,nex-10,233653,16875588,03S,"MULTILINESTRING ((1371732.563 599455.983, 1371..."
26,233654,233647,1.0,233953,14.627250,0.823,fp-11,nex-10,233654,"16875584,16875244",03S,"MULTILINESTRING ((1374862.565 598436.525, 1374..."
27,229941,233654,2.0,233955,3.143700,0.177,fp-11,nex-10,229941,27682983,03S,"MULTILINESTRING ((1375712.397 598377.556, 1375..."
28,233718,233707,1.0,233957,3.554550,1.000,fp-16,nex-12,233718,16875090,03S,"MULTILINESTRING ((1373770.643 602385.917, 1373..."
29,233665,233719,1.0,233959,12.586950,1.000,fp-13,nex-12,233665,"16875550,16875066",03S,"MULTILINESTRING ((1374862.555 605782.802, 1374..."
30,233657,233648,2.0,233962,5.315850,0.692,fp-27,nex-4,233657,"16875576,16875206",03S,"MULTILINESTRING ((1363143.001 595298.175, 1363..."
31,233656,233648,1.0,233961,2.363850,0.308,fp-27,nex-4,233656,16875578,03S,"MULTILINESTRING ((1365536.53 597112.113, 13655..."
32,233664,233695,1.0,233966,6.330599,1.000,fp-24,nex-20,233664,16875560,03S,"MULTILINESTRING ((1367261.01 601091.3, 1367273..."
33,233663,233705,1.0,233969,5.692500,0.886,fp-21,nex-20,233663,"16875562,16875558",03S,"MULTILINESTRING ((1362995.926 597617.573, 1363..."
34,233711,233705,2.0,233970,0.732600,0.114,fp-21,nex-20,233711,16875114,03S,"MULTILINESTRING ((1365003.976 598630.636, 1365..."
35,233728,233645,1.0,233971,3.124800,1.000,fp-26,nex-5,233728,16875062,03S,"MULTILINESTRING ((1367895.629 602091.982, 1367..."
36,233730,233729,1.0,233974,24.370200,1.000,fp-6,nex-5,233730,16875056,03S,"MULTILINESTRING ((1373428.131 608342.858, 1373..."